# Transfermarkt scrapping with Beautiful Soup & Selenium

## Imports

In [1]:
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

## Webdriver options

In [2]:
options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
options.add_argument('--incognito')
#options.add_argument('--headless')

driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)

/var/folders/qw/qjxyt3tn1057c6j4pl5tb03c0000gn/T/ipykernel_27524/3657650218.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)

## Create dataframes and scrap the data from Transfermarkt

In [3]:
df_1985 = pd.DataFrame()
df_1986 = pd.DataFrame()
df_1987 = pd.DataFrame()
df_1988 = pd.DataFrame()
df_1989 = pd.DataFrame()
df_1990 = pd.DataFrame()
df_1991 = pd.DataFrame()
df_1992 = pd.DataFrame()
df_1993 = pd.DataFrame()
df_1994 = pd.DataFrame()
df_1995 = pd.DataFrame()
df_1996 = pd.DataFrame()
df_1997 = pd.DataFrame()
df_1998 = pd.DataFrame()
df_1999 = pd.DataFrame()
df_2000 = pd.DataFrame()
df_2001 = pd.DataFrame()
df_2002 = pd.DataFrame()
df_2003 = pd.DataFrame()
df_2004 = pd.DataFrame()
df_2005 = pd.DataFrame()

In [152]:
driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/1")
page_source = driver.page_source
rows = []
next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
count = 2

#print(len(next_buttons))

#for x in range(len(next_buttons)):
while (len(next_buttons)!=0) :
    
    if next_buttons[0].is_displayed():

        soup = BeautifulSoup(page_source, "html.parser")
        #next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        tables = soup.find_all('table')
        table = soup.find('table', class_ = 'items')  
      
        #Collect data for odd rows  
        for row in table.tbody.find_all('tr', class_="odd"):    
        # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'France',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
            } )

        #Collect data for even rows
        for row in table.tbody.find_all('tr', class_="even"):    
        # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'France',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
            } )        


        #driver.execute_script("arguments[0].click();", next_buttons[x])
        driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/" + "" + str(count))
        page_source = driver.page_source
        next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        count +=1


page_source = driver.page_source
soup = BeautifulSoup(page_source, "html.parser")
#next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
tables = soup.find_all('table')
table = soup.find('table', class_ = 'items')  
      
#Collect data for odd rows        
for row in table.tbody.find_all('tr', class_="odd"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'France',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
    } )

#Collect data for even rows
for row in table.tbody.find_all('tr', class_="even"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'France',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
    } )  

df_2005 = pd.DataFrame(rows)               
df_2005

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Other Positions,Height,Market Value
0,12,Ilyes Housni,Centre-Forward,"May 14, 2005",18,"[Morocco, France]",France,Créteil,,"1,72",€3.00m
1,,Romaric Etonde,Centre-Forward,"Apr 30, 2005",18,"[France, Cameroon]",France,Montreuil,,,€400k
2,,Darnell Eric Bile,Centre-Forward,"Oct 28, 2005",18,"[France, Cote d'Ivoire]",France,Colombes,,,€200k
3,,Aylan Benyahia-Tani,Centre-Forward,"Jul 19, 2005",18,"[France, Algeria]",France,Marseille,,,€150k
4,91,David Tebili,Centre-Forward,"Feb 15, 2005",19,"[France, Cote d'Ivoire]",France,Évry,,"1,83",€50k
5,,Karim Boutera,Centre-Forward,"Aug 4, 2005",18,"[France, Algeria]",France,Besançon,,"1,85",-
6,19,Nathan Fernandes,Centre-Forward,"Jun 7, 2005",18,"[France, Portugal]",France,St Priest en Jarez,LW RW,"1,86",-
7,28,Sonel Gibon,Centre-Forward,"May 3, 2005",18,"[France, Martinique]",France,Lyon,RW LW,"1,66",-
8,,Ahmed Abdourazak,Centre-Forward,"Apr 17, 2005",18,"[France, Madagascar]",France,Troyes,LW RW,"1,88",-
9,,Enzo Misse,Centre-Forward,"Jun 14, 2005",18,[France],France,Annecy,,,-
10,,Yassine Djabba,Centre-Forward,"Feb 6, 2005",19,"[France, Algeria]",France,Marseille,,"1,89",-
11,9,Sofiane Achour,Centre-Forward,"Aug 21, 2005",18,"[France, Algeria]",France,,,,-
12,,Pedro Amadou,Centre-Forward,"Oct 26, 2005",18,"[France, England]",France,,RW LW,"1,88",-
13,22,Moussa Soumano,Centre-Forward,"Jul 9, 2005",18,"[France, Mali]",France,Saint-Denis,,"1,85",€600k
14,20,Simon Kalambayi,Centre-Forward,"Feb 20, 2005",19,"[France, DR Congo]",France,Mantes-la-Jolie,,"1,85",€250k
15,16,Aaron Akalé,Centre-Forward,"Apr 20, 2005",18,[France],France,Auxerre,,"1,81",€150k
16,13,Steve Ngoura,Centre-Forward,"Feb 22, 2005",19,"[France, Cameroon]",France,Ivry-sur-Seine,,"1,93",€100k
17,,Arthur Saintorens,Centre-Forward,"Mar 7, 2005",19,[France],France,Dax,,"1,83",-
18,,Rayane Souiri,Centre-Forward,"Dec 15, 2005",18,"[France, Morocco]",France,Nancy,RW LW,"1,80",-
19,,Bilal Traoré,Centre-Forward,"Jun 24, 2005",18,"[France, Mali]",France,Lille,RW AM,"1,80",-
20,,Yanis Beau Djellel,Centre-Forward,"Jan 14, 2005",19,"[France, Algeria]",France,,SS,"1,81",-
21,22,Tidiane Diawara,Centre-Forward,"Apr 29, 2005",18,"[France, Mali]",France,Évry,,"1,88",-
22,,Joseph Mangondo,Centre-Forward,"Aug 6, 2005",18,"[France, Cameroon]",France,,LW RW,"1,85",-
23,,Sandro Pagès,Centre-Forward,"Jan 4, 2005",19,[France],France,Sète,LW RW,"1,82",-
24,,Lionel Lukoki,Centre-Forward,"May 7, 2005",18,"[France, DR Congo]",France,Soisy-sous-Montmorency,RW LW,,-
25,,Baptiste Zon,Centre-Forward,"Mar 18, 2005",18,[France],France,Metz,,"1,81",-
26,,Simon Cara,Centre-Forward,"Mar 31, 2005",18,[France],France,Montpellier,,"1,82",-
27,9,Zoumana Diallo,Centre-Forward,"Feb 2, 2005",19,"[France, Mali]",France,Strasbourg,SS,"1,85",-
28,,Noah Le Bret,Centre-Forward,"Jan 16, 2005",19,[France],France,Montfermeil,RM,,-
29,,Trévis Dago,Centre-Forward,"Jan 21, 2005",19,"[France, Cote d'Ivoire]",France,Villeneuve-Saint-Georges,LW RW,"1,83",-
30,,Mohamed Bechikh,Centre-Forward,"Jul 13, 2005",18,"[France, Algeria]",France,Créteil,,"1,83",-
31,9,Léo Sahin,Centre-Forward,"Oct 30, 2005",18,"[Türkiye, France]",France,Saint-Avold,,"1,80",-
32,,Joris Manquant,Centre-Forward,"Oct 20, 2005",18,"[France, Cameroon]",France,,,"1,86",-
33,,Yanis Rafii,Centre-Forward,"Jun 26, 2005",18,"[France, Morocco]",France,Reims,,"1,86",-
34,,Mehdi Harfi,Centre-Forward,"Jan 28, 2005",19,"[Morocco, France]",France,,LW RW,,-
35,,Yohji Koré,Centre-Forward,"Dec 10, 2005",18,"[France, Cote d'Ivoire]",France,Poissy,,,-
36,,Sandro Bertolucci,Centre-Forward,"May 29, 2005",18,"[France, Italy]",France,La Seyne-sur-Mer,,,-

In [131]:
with pd.option_context('display.max_rows',None, 'display.max_columns',None):print(df_2001)

   Number                     Name        Position  Date of Birth Age
0      29           Evann Guessand  Centre-Forward   Jul 1, 2001   22  \
1       9          Willem Geubbels  Centre-Forward  Aug 16, 2001   22
2      70             Evans Maurin  Centre-Forward  Mar 30, 2001   22
3       9      Lamine Diaby-Fadiga  Centre-Forward  Jan 19, 2001   23
4      11             Amadou Ba-Sy  Centre-Forward   Jun 8, 2001   22
5      21           Mehdi Baaloudj  Centre-Forward   Feb 2, 2001   23
6      88         Yanis Guermouche  Centre-Forward  Apr 15, 2001   22
7                     Darell Tokpa  Centre-Forward   Jun 2, 2001   22
8                      Nabil Makni  Centre-Forward  Sep 29, 2001   22
9      19              Ilies Faure  Centre-Forward  Jun 28, 2001   22
10                Oscar Le Guillou  Centre-Forward  Oct 18, 2001   22
11                 Antoine Coquant  Centre-Forward   Dec 3, 2001   22
12             Loïc Amisi Kasabala  Centre-Forward  Nov 16, 2001   22
13      9        Amine El Ouazzani  Centre-Forward  Jul 15, 2001   22
14      9           Yanis Begraoui  Centre-Forward   Jul 4, 2001   22
15     19           Samuel Ntamack  Centre-Forward  Apr 27, 2001   22
16      9            Noha Ndombasi  Centre-Forward  Apr 28, 2001   22
17     19            Nesta Elphege  Centre-Forward   Jan 9, 2001   23
18     17             Jacques Siwe  Centre-Forward  Jul 29, 2001   22
19     20        Ulrick Eneme-Ella  Centre-Forward  May 22, 2001   22
20     18         Franck Rivollier  Centre-Forward  Apr 20, 2001   22
21                     Yann Fangwa  Centre-Forward  Jan 24, 2001   23
22     25              Kévin Mbala  Centre-Forward  Jan 17, 2001   23
23                 Isoumail Camara  Centre-Forward   Nov 3, 2001   22
24                      Jean Boyer  Centre-Forward  Mar 11, 2001   22
25         Olivier Cassange Nzimbu  Centre-Forward   Aug 8, 2001   22
26     77       Mehdi Dan Galibali  Centre-Forward   Jan 4, 2001   23
27                      Enzo Renou  Centre-Forward  Aug 20, 2001   22
28                     Jilo Niamké  Centre-Forward  Sep 17, 2001   22
29                   Sacha Hamache  Centre-Forward   Jan 5, 2001   23
30                   Steevy Nogbou  Centre-Forward  Apr 27, 2001   22
31                     Hugo Danjou  Centre-Forward  Mar 12, 2001   22
32                  Dylan Dalmasso  Centre-Forward  Jan 31, 2001   23
33                  Ibrahim Carlak  Centre-Forward  Nov 21, 2001   22
34     30        Sofiane El Ftouhi  Centre-Forward  Jan 26, 2001   23
35                     Steven Goma  Centre-Forward  Nov 15, 2001   22
36                 Wilfried Misiak  Centre-Forward   Oct 6, 2001   22
37     28            Isyakha Touré  Centre-Forward   Feb 2, 2001   23
38                   Maxence Puget  Centre-Forward   Mar 2, 2001   23
39                  Thomas Gautier  Centre-Forward  Jul 25, 2001   22
40            Mamadou Saliou Dramé  Centre-Forward  Dec 28, 2001   22
41     22              Thomas Gret  Centre-Forward  May 15, 2001   22
42     22              Daniel Glao  Centre-Forward  Sep 14, 2001   22
43                 Précieux N'Kaba  Centre-Forward  Mar 28, 2001   22
44                    Paul Bonneau  Centre-Forward   Jun 6, 2001   22
45     15       Gamil Abdourazakou  Centre-Forward  May 16, 2001   22
46                     Emrys Gomis  Centre-Forward   Oct 1, 2001   22
47     12               Axel Gnapi  Centre-Forward  Aug 28, 2001   22
48                     Elie Kisoka  Centre-Forward   Dec 8, 2001   22
49     14           Jordan Pothier  Centre-Forward   Feb 9, 2001   23
50                    Sami Messili  Centre-Forward  Nov 19, 2001   22
51     19               Enzo Daoud  Centre-Forward   Apr 2, 2001   22
52                  Norvin Mukiele  Centre-Forward  Feb 16, 2001   23
53     26             El Hadj Coly  Centre-Forward   Jul 5, 2001   22
54               Ridge Duah-Adusei  Centre-Forward  Mar 10, 2001   22
55             Aboubaker Es Sahhal  Centre-Forward  Jan 29, 2001   23
56                 Loïck Piquionne  Centre-Forward  Apr 17, 2001   22
57                   Sacha Guilhen  Centre-Forward  Mar 26, 2001   22
58                Giovann Couasnon  Centre-Forward   Apr 5, 2001   22
59              Méroine El Hammiri  Centre-Forward  May 23, 2001   22
60                  Nathan Malonga  Centre-Forward  Jan 15, 2001   23
61                     Yohan Greco  Centre-Forward   Jan 7, 2001   23
62                    Sonny Contri  Centre-Forward  Dec 19, 2001   22
63                    Yacine Ressa  Centre-Forward  Apr 11, 2001   22

                Nationality Birth Country            Place of Birth
0   [Cote d'Ivoire, France]        France                   Ajaccio  \
1     [France, Netherlands]        France              Villeurbanne
2                  [France]        France                 Charenton
3          [France, Guinea]        France                    Grasse
4         [France, Senegal]        France                      Nice
5         [Algeria, France]        France                     Melun
6         [Algeria, France]        France         Neuilly-sur-Seine
7   [France, Cote d'Ivoire]        France                  Colombes
8         [Tunisia, France]        France                    Cannes
9         [France, Algeria]        France                  Toulouse
10                 [France]        France                    Rennes
11                 [France]        France                      Nice
12                 [France]        France
13        [Morocco, France]        France                  Grenoble
14        [Morocco, France]        France                   Étampes
15       [France, Cameroon]        France                 Montreuil
16                 [France]        France                     Bondy
17       [France, Cameroon]        France               Saint-Denis
18       [France, Cameroon]        France             Saint-Maurice
19          [Gabon, France]        France                      Sens
20       [France, Cameroon]        France             Saint-Étienne
21                 [France]        France
22       [France, DR Congo]        France  Villeneuve-Saint-Georges
23                 [France]        France                 Compiègne
24                 [France]        France             Castelnaudary
25                 [France]        France                      Lyon
26          [France, Congo]        France                  Pontoise
27                 [France]        France               La Rochelle
28  [France, Cote d'Ivoire]        France                     Paris
29        [France, Algeria]        France                     Croix
30                 [France]        France                    Clichy
31                 [France]        France      Saint-Jean-de-Verges
32                 [France]        France
33                [Türkiye]        France         Mont-Saint-Martin
34        [France, Morocco]        France                 Perpignan
35                 [France]        France            Roissy-en-Brie
36         [France, Poland]        France                     Melun
37           [France, Mali]        France                 Montreuil
38                 [France]        France
39                 [France]        France                     Paris
40                 [France]        France                      Nice
41                 [France]        France  Saint-Julien-en-Genevois
42  [France, Cote d'Ivoire]        France                 Montreuil
43          [France, Congo]        France             Aubervilliers
44                 [France]        France                      Auch
45                 [France]        France                    Nantes
46        [France, Senegal]        France    Saint-Aubin-lès-Elbeuf
47  [France, Cote d'Ivoire]        France                   Le Mans
48       [France, DR Congo]        France                     Lille
49                 [France]        France                 Périgueux
50        [France, Algeria]        France    Le Chambon-Feugerolles
51        [France, Algeria]        France                      Lens
52       [France, DR Congo]        France
53        [France, Senegal]        France                La Tronche
54                 [France]        France                     Melun
55        [France, Morocco]        France               Montpellier
56     [France, Martinique]        France                    Rennes
57                 [France]        France                      Sète
58                 [France]        France
59        [France, Morocco]        France           Le Puy-en-Velay
60                 [France]        France                   Trappes
61          [France, Italy]        France                      Lyon
62                 [France]        France                 Marseille
63        [Algeria, France]        France                 Marseille

   Other Positions Height Market Value
0          RW   LW   1,88       €5.00m
1          RW   LW   1,85       €2.00m
2               AM   1,79        €400k
3                    1,88        €400k
4                    1,91        €300k
5          SS   LW   1,83        €300k
6                    1,92        €150k
7                    1,84        €100k
8               LW   1,84         €75k
9                    1,92         €50k
10                                   -
11                                   -
12         LW   RW                   -
13              AM   1,88       €2.00m
14         RW   LW   1,79       €1.00m
15         LW   RW   1,78        €400k
16         RW   LW   1,74        €400k
17                   1,96        €300k
18                   1,83        €200k
19                   1,84        €150k
20              RW   1,92        €100k
21                   1,90         €75k
22                   1,90         €50k
23         RW   LW   1,85            -
24         RW   SS   1,83            -
25                   1,87            -
26         LW   RW   1,87            -
27                                   -
28         SS   RW   1,75            -
29         RW   RM   1,76            -
30                                   -
31                                   -
32                   1,80            -
33                   1,85            -
34                   1,82            -
35              LW   1,83            -
36         RW   LW   1,85            -
37         RW   LW                   -
38              AM   1,87            -
39                   1,93            -
40         LW   RW   1,76            -
41                                   -
42         RW   LW   1,85            -
43              LW   1,84            -
44                                   -
45         LW   RW   1,83            -
46              LM                   -
47                   1,86            -
48                   1,80            -
49         RW   LW                   -
50         RW   LW   1,67            -
51                   1,83            -
52                   1,91            -
53         RW   LW   1,76            -
54         RW   LW                   -
55         SS   LW   1,80            -
56                   1,84            -
57         LW   RW   1,78            -
58              AM   1,76            -
59         RW   LW   1,72            -
60         LW   RW   1,78            -
61                   1,72            -
62                                   -
63                   1,88            -

## Merge all the dataframes into a single one and save the df into a csv file

In [153]:
df_merged = pd.concat([df_1985,df_1986,df_1987,df_1988,df_1989,df_1990,df_1991,df_1992,df_1993,df_1994,df_1995,df_1996,df_1997,df_1998,df_1999,df_2000,df_2001,df_2002,df_2003,df_2004,df_2005],ignore_index=True)

In [154]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1114 entries, 0 to 1113
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           1114 non-null   object
 1   Name             1114 non-null   object
 2   Position         1114 non-null   object
 3   Date of Birth    1114 non-null   object
 4   Age              1114 non-null   object
 5   Nationality      1114 non-null   object
 6   Birth Country    1114 non-null   object
 7   Place of Birth   1114 non-null   object
 8   Other Positions  1114 non-null   object
 9   Height           1114 non-null   object
 10  Market Value     1114 non-null   object
dtypes: object(11)
memory usage: 95.9+ KB

In [155]:
df_merged.to_csv("../../data/france_centerforwards.csv", header= True, index=False)

In [156]:
df_merged

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Other Positions,Height,Market Value
0,10,André-Pierre Gignac,Centre-Forward,"Dec 5, 1985",38,"[France, Mexico]",France,Martigues,LW,"1,87",€1.00m
1,,Matthieu Thirouin,Centre-Forward,"Jun 21, 1985",38,[France],France,Caen,,,-
2,,Christopher Gomis,Centre-Forward,"Sep 16, 1985",38,"[France, Senegal]",France,Maisons-Laffitte,,"1,86",-
3,,Lazhar Karboua,Centre-Forward,"Mar 20, 1985",38,[France],France,Annecy,AM,"1,80",-
4,,Farid Soltani,Centre-Forward,"Mar 10, 1985",38,"[Morocco, France]",France,Audincourt,AM,"1,78",-
...,...,...,...,...,...,...,...,...,...,...,...
1109,,Joris Manquant,Centre-Forward,"Oct 20, 2005",18,"[France, Cameroon]",France,,,"1,86",-
1110,,Yanis Rafii,Centre-Forward,"Jun 26, 2005",18,"[France, Morocco]",France,Reims,,"1,86",-
1111,,Mehdi Harfi,Centre-Forward,"Jan 28, 2005",19,"[Morocco, France]",France,,LW RW,,-
1112,,Yohji Koré,Centre-Forward,"Dec 10, 2005",18,"[France, Cote d'Ivoire]",France,Poissy,,,-
1113,,Sandro Bertolucci,Centre-Forward,"May 29, 2005",18,"[France, Italy]",France,La Seyne-sur-Mer,,,-