# Transfermarkt scrapping with Beautiful Soup & Selenium

## Imports

In [1]:
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

## Webdriver options

In [2]:
options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
options.add_argument('--incognito')
#options.add_argument('--headless')

driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)

/var/folders/qw/qjxyt3tn1057c6j4pl5tb03c0000gn/T/ipykernel_53770/3657650218.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)

## Create dataframes and scrap the data from Transfermarkt

In [3]:
df_1985 = pd.DataFrame()
df_1986 = pd.DataFrame()
df_1987 = pd.DataFrame()
df_1988 = pd.DataFrame()
df_1989 = pd.DataFrame()
df_1990 = pd.DataFrame()
df_1991 = pd.DataFrame()
df_1992 = pd.DataFrame()
df_1993 = pd.DataFrame()
df_1994 = pd.DataFrame()
df_1995 = pd.DataFrame()
df_1996 = pd.DataFrame()
df_1997 = pd.DataFrame()
df_1998 = pd.DataFrame()
df_1999 = pd.DataFrame()
df_2000 = pd.DataFrame()
df_2001 = pd.DataFrame()
df_2002 = pd.DataFrame()
df_2003 = pd.DataFrame()
df_2004 = pd.DataFrame()
df_2005 = pd.DataFrame()

In [112]:
driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/1")
page_source = driver.page_source
rows = []
next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
count = 2

#print(len(next_buttons))

#for x in range(len(next_buttons)):
while (len(next_buttons)!=0) :
    
    if next_buttons[0].is_displayed():

        soup = BeautifulSoup(page_source, "html.parser")
        #next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        tables = soup.find_all('table')
        table = soup.find('table', class_ = 'items')  
      
        #Collect data for odd rows  
        for row in table.tbody.find_all('tr', class_="odd"):    
        # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'France',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
            } )

        #Collect data for even rows
        for row in table.tbody.find_all('tr', class_="even"):    
        # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'France',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
            } )        


        #driver.execute_script("arguments[0].click();", next_buttons[x])
        driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/" + "" + str(count))
        page_source = driver.page_source
        next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        count +=1


page_source = driver.page_source
soup = BeautifulSoup(page_source, "html.parser")
#next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
tables = soup.find_all('table')
table = soup.find('table', class_ = 'items')  
      
#Collect data for odd rows        
for row in table.tbody.find_all('tr', class_="odd"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'France',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
    } )

#Collect data for even rows
for row in table.tbody.find_all('tr', class_="even"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'France',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
    } )  

df_2005 = pd.DataFrame(rows)               
df_2005

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Other Positions,Height,Market Value
0,34,Mahamadou Diawara,Central Midfield,"Feb 17, 2005",19,"[France, Mali]",France,Longjumeau,,"1,87",€3.00m
1,,Kais Chedli,Central Midfield,"Sep 16, 2005",18,"[France, Tunisia]",France,Saint-Étienne,,,-
2,,Andrei Ciobanu,Central Midfield,"Dec 9, 2005",18,"[Romania, France]",France,Créteil,AM,,-
3,,Ilyes Lim,Central Midfield,"Jan 15, 2005",19,"[France, Morocco]",France,,DM,,-
4,,Samir El Mourabet,Central Midfield,"Oct 6, 2005",18,"[Morocco, France]",France,Strasbourg,AM LW,,-
5,,Pablo Soules,Central Midfield,"Nov 30, 2005",18,[France],France,Toulouse,,"1,72",-
6,,Alvin Krizoua,Central Midfield,"Aug 25, 2005",18,"[France, Cote d'Ivoire]",France,Créteil,,"1,87",-
7,,Dehmaine Assoumani,Central Midfield,"Apr 17, 2005",18,"[France, Comoros]",France,Drancy,AM,"1,81",-
8,,Ilyes Benlebsir,Central Midfield,"Jan 11, 2005",19,"[France, Algeria]",France,Le Havre,LW RW,"1,82",-
9,67,Naïm Byar,Central Midfield,"Feb 23, 2005",19,"[Morocco, France]",France,Reims,RM RW,"1,82",-
10,,Kevyn Adèle,Central Midfield,"Apr 12, 2005",18,"[France, Guadeloupe]",France,Pontoise,DM,,-
11,,Stefan Dzodic,Central Midfield,"Mar 15, 2005",18,"[Serbia, France]",France,Montpellier,DM,"1,90",-
12,,Abdoulaye Sow,Central Midfield,"Apr 3, 2005",18,"[Guinea, France]",France,Paris,,"1,73",-
13,,Noah Lahmadi,Central Midfield,"Jan 5, 2005",19,"[France, Algeria]",France,,DM,,€100k
14,,Abdel-Amine Tran,Central Midfield,"Nov 21, 2005",18,"[France, Algeria]",France,Nogent-sur-Marne,DM AM,,-
15,18,Benjamin Idaro,Central Midfield,"Jan 26, 2005",19,[France],France,Bordeaux,,,-
16,,Florian Dewaele,Central Midfield,"Feb 25, 2005",19,[France],France,Lille,,,-
17,,Antonin Melis,Central Midfield,"May 13, 2005",18,"[France, Italy]",France,Forbach,DM,,-
18,,Jebryl Sahraoui,Central Midfield,"Feb 4, 2005",19,"[Algeria, France]",France,Marseille,,,-
19,8,Paolo Limon,Central Midfield,"Dec 5, 2005",18,[France],France,Saint-Brieuc,DM,"1,84",-
20,,Zizou Guy,Central Midfield,"Jun 30, 2005",18,"[Madagascar, France]",France,Troyes,AM,"1,75",-
21,,Antonin Marsin,Central Midfield,"Mar 29, 2005",18,"[France, Guadeloupe]",France,Lyon,RB CB,"1,80",-
22,,Louis Valentin Aboua,Central Midfield,"Mar 2, 2005",19,"[France, Cote d'Ivoire]",France,Schiltigheim,DM,"1,83",-
23,90,Adam Gueddar,Central Midfield,"Jun 1, 2005",18,"[Morocco, France]",France,Caen,AM,,-
24,,Noa Yaguoubi,Central Midfield,"Mar 2, 2005",19,"[France, Algeria]",France,Avignon,DM AM,"1,69",-
25,,Yannick Gesan,Central Midfield,"Jul 16, 2005",18,[France],France,Ivry-sur-Seine,,"1,85",-
26,39,Ugosinho,Central Midfield,"Feb 18, 2005",19,"[Portugal, France]",France,Grenoble,RM LM,"1,77",-

In [8]:
with pd.option_context('display.max_rows',None, 'display.max_columns',None):print(df_1986)

   Number               Name   Position  Date of Birth Age
0           François Chauvel  Left-Back   Aug 7, 1986   37  \
1              Jérémy Gazeau  Left-Back  Mar 10, 1986   37
2              Grégory Tomas  Left-Back   Apr 5, 1986   37
3             Samuel Camille  Left-Back   Feb 2, 1986   38
4                 John Glele  Left-Back  Feb 19, 1986   38
5          Alexandre Raineau  Left-Back  Jun 21, 1986   37
6               Walid Cherfa  Left-Back  Feb 24, 1986   38
7             Joachim Ichane  Left-Back  Jun 27, 1986   37
8             Yann Schneider  Left-Back  Jan 19, 1986   38
9             Djassem Nianzi  Left-Back  Apr 18, 1986   37
10             Erwan Dioclès  Left-Back   Apr 7, 1986   37
11               Rémy Amieux  Left-Back   Sep 5, 1986   37
12           Sofiane Batikhy  Left-Back  Jan 27, 1986   38
13              Kenny Gillet  Left-Back   Jan 3, 1986   38
14          Zoumana Bakayogo  Left-Back  Aug 17, 1986   37
15           Julian Palmieri  Left-Back   Dec 7, 1986   37
16           Florian Marange  Left-Back   Mar 3, 1986   38
17            Richard Soumah  Left-Back   Oct 6, 1986   37

                Nationality Birth Country       Place of Birth
0                  [France]        France                 Caen  \
1                  [France]        France  Montreuil-sous-Bois
2                  [France]        France           Versailles
3      [Martinique, France]        France          Saint-Denis
4           [Benin, France]        France              Belfort
5                  [France]        France                Paris
6         [Algeria, France]        France             Toulouse
7         [France, Réunion]        France                Niort
8         [France, Germany]        France           Phalsbourg
9                  [France]        France            Marseille
10                 [France]        France                Dinan
11                 [France]        France               Vienne
12                 [France]        France  Montreuil-sous-Bois
13                 [France]        France             Bordeaux
14  [Cote d'Ivoire, France]        France                Paris
15                 [France]        France                 Lyon
16                 [France]        France             Pauillac
17         [Guinea, France]        France              Créteil

   Other Positions Height Market Value
0                    1,82            -
1                    1,81            -
2                    1,70            -
3               CB   1,76            -
4                    1,80            -
5               DM   1,78            -
6               CB   1,85            -
7                    1,84            -
8                     N/A            -
9               RB   1,80            -
10                   1,72            -
11         LM   LW   1,75            -
12                   1,80            -
13         CB   DM   1,78            -
14              LM   1,75            -
15         LM   LW   1,70            -
16              CB   1,81            -
17         LM   LW   1,79            -

## Merge all the dataframes into a single one and save the df into a csv file

In [113]:
df_merged = pd.concat([df_1985,df_1986,df_1987,df_1988,df_1989,df_1990,df_1991,df_1992,df_1993,df_1994,df_1995,df_1996,df_1997,df_1998,df_1999,df_2000,df_2001,df_2002,df_2003,df_2004,df_2005],ignore_index=True)

In [115]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 735 entries, 0 to 734
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           735 non-null    object
 1   Name             735 non-null    object
 2   Position         735 non-null    object
 3   Date of Birth    735 non-null    object
 4   Age              735 non-null    object
 5   Nationality      735 non-null    object
 6   Birth Country    735 non-null    object
 7   Place of Birth   735 non-null    object
 8   Other Positions  735 non-null    object
 9   Height           735 non-null    object
 10  Market Value     735 non-null    object
dtypes: object(11)
memory usage: 63.3+ KB

In [116]:
df_merged.to_csv("../../data/france_centralmidfields.csv", header= True, index=False)

In [117]:
df_merged

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Other Positions,Height,Market Value
0,,Aziz Dahchour,Central Midfield,"Apr 21, 1985",38,"[France, Morocco]",France,Sens,AM,"1,70",€50k
1,,Grégory Kouam,Central Midfield,"Dec 30, 1985",38,[France],France,Lyon,AM,,-
2,,Thomas Delanoë,Central Midfield,"Apr 21, 1985",38,[France],France,Nantes,AM DM,"1,87",-
3,,Sébastien Vezine,Central Midfield,"Dec 6, 1985",38,[France],France,Brive la Gaillarde,,"1,88",-
4,,Arnaud Billeaux,Central Midfield,"May 6, 1985",38,[France],France,Seclin,DM AM,"1,76",-
...,...,...,...,...,...,...,...,...,...,...,...
730,,Louis Valentin Aboua,Central Midfield,"Mar 2, 2005",19,"[France, Cote d'Ivoire]",France,Schiltigheim,DM,"1,83",-
731,90,Adam Gueddar,Central Midfield,"Jun 1, 2005",18,"[Morocco, France]",France,Caen,AM,,-
732,,Noa Yaguoubi,Central Midfield,"Mar 2, 2005",19,"[France, Algeria]",France,Avignon,DM AM,"1,69",-
733,,Yannick Gesan,Central Midfield,"Jul 16, 2005",18,[France],France,Ivry-sur-Seine,,"1,85",-
734,39,Ugosinho,Central Midfield,"Feb 18, 2005",19,"[Portugal, France]",France,Grenoble,RM LM,"1,77",-