# Transfermarkt scrapping with Beautiful Soup & Selenium

## Imports

In [1]:
import re
import requests
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

## Webdriver options

In [3]:
options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
options.add_argument('--incognito')
#options.add_argument('--headless')

driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)

/var/folders/qw/qjxyt3tn1057c6j4pl5tb03c0000gn/T/ipykernel_44566/3657650218.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)

## Create dataframes and scrap the data from Transfermarkt

In [4]:
df_1985 = pd.DataFrame()
df_1986 = pd.DataFrame()
df_1987 = pd.DataFrame()
df_1988 = pd.DataFrame()
df_1989 = pd.DataFrame()
df_1990 = pd.DataFrame()
df_1991 = pd.DataFrame()
df_1992 = pd.DataFrame()
df_1993 = pd.DataFrame()
df_1994 = pd.DataFrame()
df_1995 = pd.DataFrame()
df_1996 = pd.DataFrame()
df_1997 = pd.DataFrame()
df_1998 = pd.DataFrame()
df_1999 = pd.DataFrame()
df_2000 = pd.DataFrame()
df_2001 = pd.DataFrame()
df_2002 = pd.DataFrame()
df_2003 = pd.DataFrame()
df_2004 = pd.DataFrame()
df_2005 = pd.DataFrame()

In [198]:
driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/1")
page_source = driver.page_source
rows = []
next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
count = 2

#print(len(next_buttons))

#for x in range(len(next_buttons)):
while (len(next_buttons)!=0) :
    
    if next_buttons[0].is_displayed():

        soup = BeautifulSoup(page_source, "html.parser")
        #next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        tables = soup.find_all('table')
        table = soup.find('table', class_ = 'items')  
      
      
        for row in table.tbody.find_all('tr', class_="odd"):    
    # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))    

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'France',
                'Place of Birth': columns[8].text.strip(),
                'Height' : columns[9].text.strip(), 
                'Market Value' : columns[10].text.strip()
            } )

        for row in table.tbody.find_all('tr', class_="even"):    
    # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))   

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'France',
                'Place of Birth': columns[8].text.strip(),
                'Height' : columns[9].text.strip(), 
                'Market Value' : columns[10].text.strip()
            } )        


        #driver.execute_script("arguments[0].click();", next_buttons[x])
        driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/" + "" + str(count))
        page_source = driver.page_source
        next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        count +=1


page_source = driver.page_source
soup = BeautifulSoup(page_source, "html.parser")
#next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
tables = soup.find_all('table')
table = soup.find('table', class_ = 'items')  
      
      
for row in table.tbody.find_all('tr', class_="odd"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))   

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'France',
                'Place of Birth': columns[8].text.strip(),
                'Height' : columns[9].text.strip(), 
                'Market Value' : columns[10].text.strip()
    } )

for row in table.tbody.find_all('tr', class_="even"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))   

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'France',
                'Place of Birth': columns[8].text.strip(),
                'Height' : columns[9].text.strip(), 
                'Market Value' : columns[10].text.strip()
    } )  

df_2005 = pd.DataFrame(rows)               
df_2005

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value
0,50,Guillaume Restes,Goalkeeper,"Mar 11, 2005",18,"[France, Cote d'Ivoire]",France,Toulouse,"1,88",€10.00m
1,1,Noah Raveyre,Goalkeeper,"Jun 22, 2005",18,[France],France,Le Puy-en-Velay,,€150k
2,,Grégoire Swiderski,Goalkeeper,"Oct 5, 2005",18,"[Canada, France]",France,Bruges,"1,87",€50k
3,,Ewen Jaouen,Goalkeeper,"Dec 29, 2005",18,[France],France,Paris,"2,00",€50k
4,,Yanis Baclot,Goalkeeper,"Feb 4, 2005",19,[France],France,Poissy,,-
5,,Dorian Pieroni,Goalkeeper,"May 11, 2005",18,[France],France,Cagnes-sur-Mer,"1,78",-
6,,Soan Jansenn,Goalkeeper,"Apr 4, 2005",18,[France],France,Ploemeur,,-
7,66,Quentin Beck,Goalkeeper,N/A,18,[France],France,Saint-avold,,-
8,,Amine Essomba,Goalkeeper,"Nov 27, 2005",18,[France],France,Marmande,,-
9,,Matisse Morville,Goalkeeper,"Sep 7, 2005",18,"[France, Senegal]",France,Paris,"1,86",-
10,,Ryan Tutu Mayangila,Goalkeeper,"Apr 1, 2005",18,"[DR Congo, France]",France,Melun,,-
11,,Joris Revault,Goalkeeper,"Jun 22, 2005",18,[France],France,Toulouse,,-
12,,Amine Boukemouche,Goalkeeper,"Aug 5, 2005",18,"[Algeria, France]",France,Sèvres,"1,95",-
13,30,Justin Bengui Joao,Goalkeeper,"Jul 9, 2005",18,"[France, Angola]",France,Montbéliard,"1,90",€300k
14,,Alane Bedfian,Goalkeeper,"Jun 25, 2005",18,[France],France,Paris,,€50k
15,,Alexis Mirbach,Goalkeeper,"Mar 4, 2005",18,[France],France,Metz,"1,92",€50k
16,,Maxence Caron,Goalkeeper,"Jan 7, 2005",19,[France],France,Blendecques,,-
17,,Tom Bachetti-Vannson,Goalkeeper,"Feb 25, 2005",19,[France],France,Cuers,"1,78",-
18,,Theo Folgado,Goalkeeper,"Jan 27, 2005",19,"[France, Spain]",France,Bayonne,,-
19,,Leny Beranto,Goalkeeper,"Feb 22, 2005",19,"[France, Togo]",France,Anthony,,-
20,,Lukas Mary,Goalkeeper,"Feb 24, 2005",19,[France],France,Chambray-lès-Tours,,-
21,,Khamy Bello,Goalkeeper,"Mar 15, 2005",18,"[France, Senegal]",France,Rouen,,-
22,,Viali,Goalkeeper,"Mar 10, 2005",18,"[Portugal, France]",France,Nantes,,-
23,,Louis Petitaud,Goalkeeper,"Feb 4, 2005",19,[France],France,Privas,,-
24,,Lucas Droyaux,Goalkeeper,"Jan 28, 2005",19,[France],France,Vannes,,-
25,,Théo Ramousse,Goalkeeper,"Feb 6, 2005",19,[France],France,,"1,89",-
26,,Kenzo Vilon Guezo,Goalkeeper,"Apr 28, 2005",18,"[France, Benin]",France,Bondy,,-
27,,Théo Udin,Goalkeeper,"Jul 19, 2005",18,[France],France,,"1,88",-
28,,Baris Degermenci,Goalkeeper,"Mar 22, 2005",18,"[Türkiye, France]",France,,,-
29,,Matéo Gonzalez,Goalkeeper,"Sep 17, 2005",18,"[France, Spain]",France,Troyes,,-
30,,Matéo Pereira,Goalkeeper,"Oct 15, 2005",18,"[France, Portugal]",France,Ambérieu-en-Bugey,,-
31,,Ibrahim Diarra,Goalkeeper,"Jun 13, 2005",18,"[France, Mali]",France,Melun,,-
32,,El Nasry Mistoihi,Goalkeeper,"Mar 27, 2005",18,"[France, Comoros]",France,,"1,86",-
33,,Lisandru Olmeta,Goalkeeper,"Jul 21, 2005",18,[France],France,Ajaccio,"1,90",-
34,,Maël Biczo,Goalkeeper,"Nov 17, 2005",18,[France],France,Pabu,,-
35,,Houssam Karoui,Goalkeeper,"Sep 22, 2005",18,"[France, Tunisia]",France,Paris,"1,85",-
36,,Maxime Debove,Goalkeeper,"Sep 9, 2005",18,[France],France,Carcassonne,"1,83",-
37,,Nathanaël Follet,Goalkeeper,"Jun 18, 2005",18,[France],France,,"1,85",-
38,,Kélis Fizet,Goalkeeper,"Mar 18, 2005",18,[France],France,Rouen,"1,90",-
39,,Raphaël Ben Taib,Goalkeeper,"Mar 26, 2005",18,"[Algeria, France]",France,Harfleur,,-
40,,Arthur Tirard Collet,Goalkeeper,"Mar 14, 2005",18,[France],France,Chambéry,,-
41,,Desthy Nkounkou,Goalkeeper,"Mar 11, 2005",18,"[France, Congo]",France,Melun,"1,90",-

In [142]:
with pd.option_context('display.max_rows',None, 'display.max_columns',None):print(df_2002)

   Number                   Name    Position  Date of Birth Age
0      16             Théo Borne  Goalkeeper  Jul 15, 2002   21  \
1                  Elias Damergy  Goalkeeper  Oct 17, 2002   21
2       1         Lenny Montfort  Goalkeeper  Jan 16, 2002   22
3                   Amjhad Nazih  Goalkeeper  Jan 18, 2002   22
4      16  Owen-Césaire Matimbou  Goalkeeper  Jun 19, 2002   21
5             Dorian Maciejewski  Goalkeeper   Jan 2, 2002   22
6                 Pierre Brignon  Goalkeeper   Apr 8, 2002   21
7              Keyvan Mottaghian  Goalkeeper  Nov 16, 2002   21
8               Ebenesere Koudou  Goalkeeper  Jul 17, 2002   21
9                Quentin Manteau  Goalkeeper  Jun 13, 2002   21
10               Kamille Sauvage  Goalkeeper  Jan 11, 2002   22
11            Mathieu Pastorelli  Goalkeeper  May 31, 2002   21
12                 Elouan Collet  Goalkeeper  Apr 20, 2002   21
13     30   Ghjuvanni Quilichini  Goalkeeper   Sep 1, 2002   21
14     16           Melvin Zinga  Goalkeeper  Mar 16, 2002   21
15     30       Matthieu Rongier  Goalkeeper  Apr 10, 2002   21
16     40           Rudy Boulais  Goalkeeper  May 19, 2002   21
17     30     Augustin Delbecque  Goalkeeper   Feb 3, 2002   22
18              Sofiane Mahmoudi  Goalkeeper  Apr 10, 2002   21
19     30         Kylian Alfonsi  Goalkeeper  Jan 25, 2002   22
20            Kélian Guillemette  Goalkeeper  Oct 23, 2002   21
21               Killian Grémont  Goalkeeper  Jun 22, 2002   21
22     30          Ylies Zitouni  Goalkeeper   May 9, 2002   21
23                    Enzo Sulas  Goalkeeper  Aug 27, 2002   21
24                 Axel Réveille  Goalkeeper  Mar 20, 2002   21
25                Fei-Hong Faham  Goalkeeper   Aug 1, 2001   22
26         Yassine Gourari Tebaa  Goalkeeper  Apr 13, 2001   22
27                  Thomas Perez  Goalkeeper   Feb 1, 2001   23
28              Nassim El Hamine  Goalkeeper  Nov 14, 2001   22
29                Baptiste Davaï  Goalkeeper  Oct 29, 2001   22
30      1       Vincent Fournier  Goalkeeper  May 12, 2001   22
31                   Luis Orfait  Goalkeeper  Nov 27, 2001   22
32                 Jules Rolland  Goalkeeper  Mar 31, 2001   22
33               Maxence Bellamy  Goalkeeper  Apr 10, 2001   22
34               Antonin Parisot  Goalkeeper  Jul 28, 2001   22
35                  Kary Guarino  Goalkeeper  Jun 19, 2001   22
36               Louis Guivarc'h  Goalkeeper  Sep 10, 2001   22
37               Anthony Laurent  Goalkeeper   Nov 2, 2001   22
38                Hugo Stevenart  Goalkeeper  Jun 27, 2001   22
39                 Théo Beauciel  Goalkeeper  Apr 19, 2001   22
40                Jorys Mohimont  Goalkeeper   Jun 1, 2001   22
41            Julien Linguanotto  Goalkeeper  Jul 28, 2001   22
42     20          Michel Fohouo  Goalkeeper  Aug 31, 2001   22
43      1        Titouan Guillou  Goalkeeper  Nov 12, 2001   22
44     16         Stanley Kouamé  Goalkeeper   Aug 2, 2001   22
45     30         Melvyn Ravalet  Goalkeeper  Mar 14, 2001   22
46               Théo Cozzi-Buet  Goalkeeper  Feb 25, 2001   23
47                  Alexis Wolff  Goalkeeper  Jan 29, 2001   23
48                  Rémi Piquard  Goalkeeper   Jan 2, 2001   23
49                Julien Crombez  Goalkeeper   Apr 6, 2001   22
50                 Thomas Allard  Goalkeeper  Apr 23, 2002   21
51               Willem Pronzola  Goalkeeper   Mar 6, 2002   21
52                Enzo Fernandes  Goalkeeper  May 26, 2002   21
53                     Macéo Sow  Goalkeeper  Feb 14, 2002   22
54     16           Arthur Arias  Goalkeeper   Jan 1, 2002   22
55                  Théo Zeghbab  Goalkeeper  Jul 31, 2002   21
56     51          Kévin Ousmane  Goalkeeper  Feb 22, 2002   22
57                 Julien Branco  Goalkeeper  May 13, 2002   21
58     40           Thomas Roche  Goalkeeper  Feb 21, 2002   22
59      1              Manu Agro  Goalkeeper  Jun 14, 2002   21
60     16            Fabio Vanni  Goalkeeper  Jul 20, 2002   21
61                   Enzo Dupuis  Goalkeeper   Aug 7, 2002   21
62               Mathieu Veyrier  Goalkeeper  Jun 24, 2002   21
63     16          Yanis Maronne  Goalkeeper  Apr 20, 2002   21
64                Estébane Picot  Goalkeeper   Apr 2, 2002   21
65                   Evan Marino  Goalkeeper   Feb 5, 2002   22
66            Darren Lima Semedo  Goalkeeper  Apr 27, 2002   21
67                 Yanis Bourbia  Goalkeeper  Mar 24, 2002   21

                Nationality Birth Country         Place of Birth Height
0                  [France]        France            Montbéliard   1,91  \
1         [Tunisia, France]        France        Mantes-la-Jolie   1,86
2                  [France]        France                  Redon   1,89
3         [Morocco, France]        France                   Sète   1,92
4           [France, Congo]        France                  Paris   1,95
5                  [France]        France          Fontainebleau
6                  [France]        France                  Sedan
7       [Afghanistan, Iran]        France                  Paris   1,85
8   [France, Cote d'Ivoire]        France      Clichy-la-Garenne
9                  [France]        France                  Évian   1,83
10                 [France]        France               Le Havre   1,98
11          [France, Italy]        France                   Nice   1,82
12                 [France]        France                  Nîmes
13                 [France]        France                Ajaccio   1,82
14                 [France]        France          Montivilliers   1,87
15                 [France]        France                 Amiens
16        [France, Algeria]        France                  Rouen   1,88
17                 [France]        France              Tourcoing   1,87
18                 [France]        France  Saint-Germain-en-Laye   1,85
19                 [France]        France                          1,80
20                 [France]        France                Pontivy
21                 [France]        France                 Fécamp   1,81
22        [France, Algeria]        France             Strasbourg   1,98
23          [France, Italy]        France                Aubagne   1,86
24                 [France]        France                  Nîmes   1,83
25  [France, French Guiana]        France                  Paris
26        [France, Morocco]        France          Aubergenville
27                 [France]        France              Granville
28                 [France]        France
29                 [France]        France                Lannion
30                 [France]        France               Beaumont   1,86
31                 [France]        France                  Lille
32                 [France]        France                   Nice   1,83
33                 [France]        France                 Saumur
34                 [France]        France            Montbéliard
35        [Comoros, France]        France              Marseille
36                 [France]        France          Châteaubriant
37                 [France]        France              Brennilis
38                 [France]        France  Saint-Martin-Boulogne
39                 [France]        France                  Tours
40        [France, Algeria]        France               Toulouse   1,85
41                 [France]        France                 Rennes   1,80
42  [Switzerland, Cameroon]        France                  Paris   1,86
43                 [France]        France                  Massy   1,93
44                 [France]        France        Lagny-sur-Marne   1,88
45                 [France]        France                 Amilly
46                 [France]        France       Bourgoin-Jallieu   1,86
47                 [France]        France              Perpignan   1,77
48                 [France]        France                 Hyères
49                 [France]        France                  Croix
50                 [France]        France                 Pessac   1,90
51     [France, Martinique]        France              Montreuil
52                 [France]        France                  Brest
53         [France, Guinea]        France                Le Mans   1,85
54                 [France]        France   Châlons-en-Champagne   1,89
55        [France, Algeria]        France                Castres
56           [France, Mali]        France                   Lyon   1,87
57       [France, Portugal]        France              Montluçon   1,92
58                 [France]        France                 Meudon   1,85
59  [France, Cote d'Ivoire]        France                  Paris   1,91
60          [France, Italy]        France                Aubagne   1,81
61          [France, Italy]        France                 Cannes   1,89
62                 [France]        France                 Vienne
63                 [France]        France       Clermont-Ferrand   1,84
64                 [France]        France              Avranches   1,83
65          [France, Italy]        France                Orléans   1,83
66     [France, Cape Verde]        France              Le Cannet   1,90
67        [France, Algeria]        France                  Paris   1,80

   Market Value
0         €100k
1         €100k
2          €50k
3          €50k
4          €25k
5             -
6             -
7             -
8             -
9             -
10            -
11            -
12            -
13        €100k
14        €100k
15         €50k
16         €50k
17         €25k
18            -
19            -
20            -
21            -
22            -
23            -
24            -
25            -
26            -
27            -
28            -
29            -
30            -
31            -
32            -
33            -
34            -
35            -
36            -
37            -
38            -
39            -
40            -
41            -
42            -
43            -
44            -
45            -
46            -
47            -
48            -
49            -
50            -
51            -
52            -
53            -
54            -
55            -
56            -
57            -
58            -
59            -
60            -
61            -
62            -
63            -
64            -
65            -
66            -
67            -

## Merge all the dataframes into a single one and save the df into a csv file

In [199]:
df_merged = pd.concat([df_1985,df_1986,df_1987,df_1988,df_1989,df_1990,df_1991,df_1992,df_1993,df_1994,df_1995,df_1996,df_1997,df_1998,df_1999,df_2000,df_2001,df_2002,df_2003,df_2004,df_2005],ignore_index=True)

In [200]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 962 entries, 0 to 961
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Number          962 non-null    object
 1   Name            962 non-null    object
 2   Position        962 non-null    object
 3   Date of Birth   962 non-null    object
 4   Age             962 non-null    object
 5   Nationality     962 non-null    object
 6   Birth Country   962 non-null    object
 7   Place of Birth  962 non-null    object
 8   Height          962 non-null    object
 9   Market Value    962 non-null    object
dtypes: object(10)
memory usage: 75.3+ KB

In [201]:
df_merged.to_csv("../../data/france_goalkeepers.csv", header= True, index=False)

In [202]:
df_merged

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value
0,16,Jean-Louis Leca,Goalkeeper,"Sep 21, 1985",38,[France],France,Bastia,"1,80",€200k
1,,Mathieu Suffissais,Goalkeeper,"May 30, 1985",38,[France],France,Laval,"1,83",-
2,,Gérald Delaporte,Goalkeeper,"Dec 18, 1985",38,[France],France,,,-
3,,Thomas Fedrigo,Goalkeeper,"May 10, 1985",38,"[France, Italy]",France,Paray-le-Monial,"1,80",-
4,,Florian Piolot,Goalkeeper,"Dec 24, 1985",38,[France],France,Pabu,"1,86",-
...,...,...,...,...,...,...,...,...,...,...
957,,Nathanaël Follet,Goalkeeper,"Jun 18, 2005",18,[France],France,,"1,85",-
958,,Kélis Fizet,Goalkeeper,"Mar 18, 2005",18,[France],France,Rouen,"1,90",-
959,,Raphaël Ben Taib,Goalkeeper,"Mar 26, 2005",18,"[Algeria, France]",France,Harfleur,,-
960,,Arthur Tirard Collet,Goalkeeper,"Mar 14, 2005",18,[France],France,Chambéry,,-
961,,Desthy Nkounkou,Goalkeeper,"Mar 11, 2005",18,"[France, Congo]",France,Melun,"1,90",-