# Transfermarkt scrapping with Beautiful Soup & Selenium

## Imports

In [1]:
import re
import requests
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

## Webdriver options

In [2]:
options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
options.add_argument('--incognito')
#options.add_argument('--headless')

driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)

/var/folders/qw/qjxyt3tn1057c6j4pl5tb03c0000gn/T/ipykernel_55605/3657650218.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)

## Create dataframes and scrap the data from Transfermarkt

In [3]:
df_1985 = pd.DataFrame()
df_1986 = pd.DataFrame()
df_1987 = pd.DataFrame()
df_1988 = pd.DataFrame()
df_1989 = pd.DataFrame()
df_1990 = pd.DataFrame()
df_1991 = pd.DataFrame()
df_1992 = pd.DataFrame()
df_1993 = pd.DataFrame()
df_1994 = pd.DataFrame()
df_1995 = pd.DataFrame()
df_1996 = pd.DataFrame()
df_1997 = pd.DataFrame()
df_1998 = pd.DataFrame()
df_1999 = pd.DataFrame()
df_2000 = pd.DataFrame()
df_2001 = pd.DataFrame()
df_2002 = pd.DataFrame()
df_2003 = pd.DataFrame()
df_2004 = pd.DataFrame()
df_2005 = pd.DataFrame()

In [218]:
#driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/1")
page_source = driver.page_source
rows = []
next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
count = 2

#print(len(next_buttons))

#for x in range(len(next_buttons)):
while (len(next_buttons)!=0) :
    
    if next_buttons[0].is_displayed():

        soup = BeautifulSoup(page_source, "html.parser")
        #next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        tables = soup.find_all('table')
        table = soup.find('table', class_ = 'items')  
      
        #Collect data for odd rows  
        for row in table.tbody.find_all('tr', class_="odd"):    
        # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Brazil',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
            } )

        #Collect data for even rows
        for row in table.tbody.find_all('tr', class_="even"):    
        # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Brazil',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
            } )        


        #driver.execute_script("arguments[0].click();", next_buttons[x])
        #driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/" + "" + str(count))
        page_source = driver.page_source
        next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        count +=1


page_source = driver.page_source
soup = BeautifulSoup(page_source, "html.parser")
#next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
tables = soup.find_all('table')
table = soup.find('table', class_ = 'items')  
      
#Collect data for odd rows        
for row in table.tbody.find_all('tr', class_="odd"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Brazil',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
    } )

#Collect data for even rows
for row in table.tbody.find_all('tr', class_="even"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Brazil',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
    } )  

df_2005 = pd.DataFrame(rows)               
df_2005

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Other Positions,Height,Market Value
0,29,Paulinho Babilônia,Right-Back,"May 23, 2005",18,[Brazil],Brazil,Manaus,,"1,75",€500k
1,,Bruno Porto,Right-Back,"Jan 10, 2005",19,[Brazil],Brazil,,,"1,77",-
2,,Antony,Right-Back,"Jun 14, 2005",18,[Brazil],Brazil,,,"1,68",-
3,,Julio Cesar Cagnini,Right-Back,"Apr 8, 2005",18,"[Brazil, Italy]",Brazil,,DM CB,"1,79",-
4,13,Vitinho,Right-Back,"Aug 17, 2005",18,[Brazil],Brazil,,,,-
5,,Gustavo Henrique,Right-Back,"Apr 7, 2005",18,[Brazil],Brazil,,DM,,-
6,,Karan,Right-Back,"Jan 11, 2005",19,[Brazil],Brazil,Campo Bom,DM,"1,80",-
7,,Kadu Santos,Right-Back,"Aug 16, 2005",18,[Brazil],Brazil,,,"1,77",-
8,12,Gilberto Junior,Right-Back,"Mar 27, 2005",18,[Brazil],Brazil,São Paulo,RM,"1,65",-
9,,Vinycius,Right-Back,"Apr 2, 2005",18,[Brazil],Brazil,Curitiba,RW,"1,82",-
10,,Hernandes,Right-Back,"Mar 11, 2005",19,[Brazil],Brazil,,,,-
11,,PH,Right-Back,"Jul 25, 2005",18,[Brazil],Brazil,,,,-
12,,Guilherme Costa,Right-Back,"Sep 3, 2005",18,[Brazil],Brazil,,,,-
13,2,Igor Schlemper,Right-Back,"Mar 1, 2005",19,[Brazil],Brazil,Balneário Camboriú,,,-
14,,Santa Cruz,Right-Back,"Jan 24, 2005",19,[Brazil],Brazil,,,,-
15,,Netinho,Right-Back,"Mar 6, 2005",19,[Brazil],Brazil,João Pessoa,,,-
16,,Gabriel Simples,Right-Back,"Jan 18, 2005",19,[Brazil],Brazil,,DM,"1,79",-
17,,Valter,Right-Back,"May 12, 2005",18,[Brazil],Brazil,Mogi Mirim,,,-
18,,Cabelo,Right-Back,"Sep 3, 2005",18,[Brazil],Brazil,Rio de Janeiro,,,-

In [143]:
with pd.option_context('display.max_rows',None, 'display.max_columns',None):print(df_1999)

   Number                Name    Position  Date of Birth Age      Nationality
0      12       Emerson Royal  Right-Back  Jan 14, 1999   25  [Brazil, Spain]  \
1           Matheus Alexandre  Right-Back   Apr 7, 1999   24         [Brazil]
2                    Weverton  Right-Back  Jun 15, 1999   24         [Brazil]
3      22           Dani Bolt  Right-Back  Jun 18, 1999   24         [Brazil]
4       2  Felipe Albuquerque  Right-Back  Sep 27, 1999   24         [Brazil]
5                       Rhuan  Right-Back  Aug 14, 1999   24         [Brazil]
6                      Wisney  Right-Back  Jun 10, 1999   24         [Brazil]
7      13       Marcelo Benia  Right-Back   Mar 1, 1999   25         [Brazil]
8             Mattheus Madson  Right-Back  Aug 20, 1999   24         [Brazil]
9                      Sandro  Right-Back  Nov 12, 1999   24         [Brazil]
10                     Adryel  Right-Back  Jun 29, 1999   24         [Brazil]
11                Luiz Felipe  Right-Back   Mar 2, 1999   25         [Brazil]
12               David Filipe  Right-Back  Jul 27, 1999   24         [Brazil]
13     22             Vitinho  Right-Back  Jul 23, 1999   24         [Brazil]
14                     Warley  Right-Back  Sep 17, 1999   24         [Brazil]
15     22           Léo Alaba  Right-Back   Jul 1, 1999   24         [Brazil]
16     33        Igor Formiga  Right-Back   Jan 8, 1999   25         [Brazil]
17                 Léo Duarte  Right-Back  Mar 23, 1999   24         [Brazil]
18                    Ericson  Right-Back  May 11, 1999   24         [Brazil]
19                    Uinatan  Right-Back  Jan 23, 1999   25         [Brazil]
20          Guilherme Radeche  Right-Back  Aug 30, 1999   24         [Brazil]
21              Júnior Santos  Right-Back   Dec 4, 1999   24         [Brazil]
22                    Germano  Right-Back   Jul 9, 1999   24         [Brazil]
23               Samuel Vitor  Right-Back           N/A   24         [Brazil]
24                 Bruno Boca  Right-Back  Jun 21, 1999   24         [Brazil]
25                    Clayton  Right-Back  Feb 27, 1999   25         [Brazil]
26                    Fellipe  Right-Back  Dec 31, 1999   24         [Brazil]
27               Igor Mathias  Right-Back  Feb 15, 1999   25         [Brazil]
28     22     Lucas Landsmann  Right-Back   Aug 3, 1999   24         [Brazil]
29                      Lessa  Right-Back  Oct 25, 1999   24         [Brazil]
30                   Fernando  Right-Back  Jan 27, 1999   25         [Brazil]
31                Mateus Cata  Right-Back  Jan 21, 1999   25         [Brazil]
32                        Ian  Right-Back  Feb 11, 1999   25         [Brazil]
33           Fernando Pileggi  Right-Back   Jul 6, 1999   24         [Brazil]
34             Gabriel Biteco  Right-Back  May 22, 1999   24         [Brazil]
35                   Cuadrado  Right-Back   Jan 6, 1999   25         [Brazil]
36                      Gutti  Right-Back  Mar 16, 1999   24         [Brazil]
37                   Nicholas  Right-Back   Mar 4, 1999   25         [Brazil]
38     23     Rodrigo Negueba  Right-Back  May 20, 1999   24         [Brazil]
39     96  Marquinhos Carioca  Right-Back  Dec 13, 1999   24         [Brazil]
40           Matheus Siqueira  Right-Back  Feb 19, 1999   25         [Brazil]
41                    Henrick  Right-Back  May 26, 1999   24         [Brazil]
42                Caio Felipe  Right-Back  Sep 24, 1999   24         [Brazil]
43               Douglas Pelé  Right-Back  Aug 25, 1999   24         [Brazil]
44                  Léo Silva  Right-Back  Apr 17, 1999   24         [Brazil]
45                     Samuel  Right-Back   Jun 6, 1999   24         [Brazil]
46              Felipe Santos  Right-Back   May 3, 1999   24         [Brazil]
47                     Wesley  Right-Back  Apr 13, 1999   24         [Brazil]
48               Júlio Amorim  Right-Back  Jan 29, 1999   25         [Brazil]
49                  Cleubinho  Right-Back  Mar 30, 1999   24         [Brazil]
50               Cayo Tenório  Right-Back  Feb 22, 1999   25         [Brazil]
51            Lucas Rodrigues  Right-Back   Jul 4, 1999   24         [Brazil]
52                Caio Felipe  Right-Back   Feb 2, 1999   25         [Brazil]
53               Lucas Ferron  Right-Back  Mar 18, 1999   24         [Brazil]
54                      Ynaiã  Right-Back  Jun 21, 1999   24         [Brazil]
55                   Coutinho  Right-Back  Apr 22, 1999   24         [Brazil]
56     13             Ronaldo  Right-Back  Mar 10, 1999   25         [Brazil]
57                Yann Baldez  Right-Back  Feb 21, 1999   25         [Brazil]
58                    Kennidy  Right-Back   Sep 9, 1999   24         [Brazil]
59            Leandro Córdova  Right-Back   Mar 6, 1999   25         [Brazil]
60           Gabriel Silveira  Right-Back  Mar 27, 1999   24         [Brazil]
61               Lucas Minele  Right-Back  Feb 15, 1999   25         [Brazil]
62           Matheus Pimentel  Right-Back  Jan 29, 1999   25         [Brazil]
63                       Yuan  Right-Back  Jun 15, 1999   24         [Brazil]
64                    Willian  Right-Back  May 21, 1999   24         [Brazil]
65             Eduardo Blanco  Right-Back  Apr 13, 1999   24         [Brazil]
66                     Eldder  Right-Back  May 14, 1999   24         [Brazil]
67                  Wellisson  Right-Back   Mar 1, 1999   25         [Brazil]
68                 Marcelinho  Right-Back  Mar 27, 1999   24         [Brazil]
69      2        Luiz Gustavo  Right-Back   Sep 2, 1999   24         [Brazil]
70                      Elias  Right-Back  Jul 16, 1999   24         [Brazil]
71               Pedro Chagas  Right-Back  May 22, 1999   24  [Brazil, Italy]

   Birth Country         Place of Birth Other Positions Height Market Value
0         Brazil              São Paulo         RM   CB   1,83      €18.00m
1         Brazil                Marília                   1,88       €1.20m
2         Brazil                 Maceió                   1,81        €800k
3         Brazil         Rio de Janeiro                   1,83        €400k
4         Brazil         Nova Andradina                   1,74        €250k
5         Brazil         Rio de Janeiro              DM   1,78         €50k
6         Brazil              Itumbiara         RM   RW   1,80         €50k
7         Brazil     Caxias do Sul (RS)                   1,76            -
8         Brazil          Novo Hamburgo              LB   1,75            -
9         Brazil                                     DM                   -
10        Brazil                                                          -
11        Brazil              Paraguaçu                                   -
12        Brazil                                          1,76            -
13        Brazil         Belo Horizonte              LB   1,74       €5.00m
14        Brazil                 Recife         RW   RM   1,72        €800k
15        Brazil                                RM   LB   1,83        €600k
16        Brazil         Rio de Janeiro              RM   1,77        €400k
17        Brazil                  Salto                   1,75        €200k
18        Brazil               Campinas              CB   1,84         €50k
19        Brazil                                          1,69            -
20        Brazil                                                          -
21        Brazil                                     RM   1,79            -
22        Brazil              Fortaleza              CB   1,74            -
23        Brazil    Senador Canedo (GO)         LB   DM   1,76            -
24        Brazil                                     AM   1,83            -
25        Brazil              Eunápolis              DM   1,72            -
26        Brazil         Belo Horizonte              RB                   -
27        Brazil                                          1,69            -
28        Brazil              São Paulo         CB   LB   1,82            -
29        Brazil                                          1,76            -
30        Brazil                                                          -
31        Brazil         Caxambu do Sul                   1,71            -
32        Brazil               Teresina                   1,69            -
33        Brazil              São Paulo         RM   DM   1,71            -
34        Brazil           Porto Alegre              RM                   -
35        Brazil                Vitória                   1,78            -
36        Brazil                Erechim              DM   1,76            -
37        Brazil                                          1,78            -
38        Brazil               São Luís              RM   1,81            -
39        Brazil         Rio de Janeiro              RW   1,78            -
40        Brazil            São Gonçalo         RM   DM   1,74            -
41        Brazil                                                          -
42        Brazil                                          1,83            -
43        Brazil              Arcoverde         DM   RM   1,71            -
44        Brazil                                          1,74            -
45        Brazil               Gravataí         DM   CB   1,77            -
46        Brazil    Monte Azul Paulista                   1,72            -
47        Brazil                                          1,68            -
48        Brazil                                          1,75            -
49        Brazil                                          1,65            -
50        Brazil         Rio de Janeiro         DM   CB   1,73            -
51        Brazil           Pouso Alegre                   1,78            -
52        Brazil         Rio de Janeiro              RM   1,77            -
53        Brazil                                     RW   1,75            -
54        Brazil                  Jales              RW   1,77            -
55        Brazil             Bataguassu         RM   RW   1,71            -
56        Brazil          Mimoso do Sul                   1,81            -
57        Brazil               São Luís                   1,79            -
58        Brazil  Monte Alegre de Minas              RW   1,69            -
59        Brazil               Criciúma              RW   1,81            -
60        Brazil                                                          -
61        Brazil                                DM   LB   1,69            -
62        Brazil                                                          -
63        Brazil                                                          -
64        Brazil         Rio de Janeiro                                   -
65        Brazil                                     CM   1,73            -
66        Brazil                                                          -
67        Brazil               Camaçari                   1,77            -
68        Brazil                                                          -
69        Brazil                  Belém              RM   1,75            -
70        Brazil                                     DM   1,81            -
71        Brazil              Forteleza                   1,83            -

## Merge all the dataframes into a single one and save the df into a csv file

In [219]:
df_merged = pd.concat([df_1985,df_1986,df_1987,df_1988,df_1989,df_1990,df_1991,df_1992,df_1993,df_1994,df_1995,df_1996,df_1997,df_1998,df_1999,df_2000,df_2001,df_2002,df_2003,df_2004,df_2005],ignore_index=True)

In [220]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1045 entries, 0 to 1044
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           1045 non-null   object
 1   Name             1045 non-null   object
 2   Position         1045 non-null   object
 3   Date of Birth    1045 non-null   object
 4   Age              1045 non-null   object
 5   Nationality      1045 non-null   object
 6   Birth Country    1045 non-null   object
 7   Place of Birth   1045 non-null   object
 8   Other Positions  1045 non-null   object
 9   Height           1045 non-null   object
 10  Market Value     1045 non-null   object
dtypes: object(11)
memory usage: 89.9+ KB

In [221]:
df_merged.to_csv("../../data/brazil/brazil_rightbacks.csv", header= True, index=False)