## Imports

In [1]:
import pandas as pd

In [2]:
df_global = pd.DataFrame

In [3]:
df_global = pd.read_csv("../../data/england/england_global.csv")

In [4]:
df_global.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9233 entries, 0 to 9232
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           3335 non-null   float64
 1   Name             9233 non-null   object
 2   Position         9233 non-null   object
 3   Date of Birth    9233 non-null   object
 4   Age              9233 non-null   object
 5   Nationality      9233 non-null   object
 6   Birth Country    9233 non-null   object
 7   Place of Birth   8871 non-null   object
 8   Height           7185 non-null   object
 9   Market Value     9233 non-null   object
 10  Main Position    8281 non-null   object
 11  Other Positions  5438 non-null   object
dtypes: float64(1), object(11)
memory usage: 865.7+ KB

In [5]:
df_global.tail()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Main Position,Other Positions
9228,NaN,Kian Le Fondre,Centre-Forward,"Feb 2, 2005",19,"['Scotland', 'England']",England,Stockport,NaN,-,Striker,RW LW
9229,NaN,Tobi Adeyemo,Centre-Forward,"Mar 14, 2005",19,"['England', 'Nigeria']",England,London,NaN,-,Striker,NaN
9230,64.0,Sonny Finch,Centre-Forward,"Aug 5, 2005",18,['England'],England,Sunderland,NaN,-,Striker,SS
9231,14.0,Dajaune Brown,Centre-Forward,"Oct 16, 2005",18,"['Jamaica', 'England']",England,Nottingham,NaN,-,Striker,NaN
9232,22.0,Emre Tezgel,Centre-Forward,"Sep 19, 2005",18,"['Türkiye', 'England']",England,Burton,"1,82",-,Striker,NaN

## Split the nationalities column

In [6]:
df_global['Nationality'] = df_global['Nationality'].str.replace("[", "")
df_global['Nationality'] = df_global['Nationality'].str.replace("'", "")
df_global['Nationality'] = df_global['Nationality'].str.replace("]", "")

In [7]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Main Position,Other Positions
0,33.0,Scott Carson,Goalkeeper,"Sep 3, 1985",38,England,England,Whitehaven,"1,88",€200k,NaN,NaN
1,NaN,Luke McShane,Goalkeeper,"Nov 6, 1985",38,England,England,Peterborough,"1,85",-,NaN,NaN
2,NaN,Jacob Giles,Goalkeeper,"Oct 12, 1985",38,England,England,Huddersfield,NaN,-,NaN,NaN
3,NaN,Greg Smith,Goalkeeper,"May 30, 1985",38,England,England,Stoke-on-Trent,NaN,-,NaN,NaN
4,NaN,Tim Deasy,Goalkeeper,"Oct 1, 1985",38,England,England,Salford,"1,85",-,NaN,NaN

In [8]:
df_global[['Nationality 1', 'Nationality 2']] = df_global['Nationality'].str.split(",",expand=True)

## Split the other positions

In [9]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Main Position,Other Positions,Nationality 1,Nationality 2
0,33.0,Scott Carson,Goalkeeper,"Sep 3, 1985",38,England,England,Whitehaven,"1,88",€200k,NaN,NaN,England,None
1,NaN,Luke McShane,Goalkeeper,"Nov 6, 1985",38,England,England,Peterborough,"1,85",-,NaN,NaN,England,None
2,NaN,Jacob Giles,Goalkeeper,"Oct 12, 1985",38,England,England,Huddersfield,NaN,-,NaN,NaN,England,None
3,NaN,Greg Smith,Goalkeeper,"May 30, 1985",38,England,England,Stoke-on-Trent,NaN,-,NaN,NaN,England,None
4,NaN,Tim Deasy,Goalkeeper,"Oct 1, 1985",38,England,England,Salford,"1,85",-,NaN,NaN,England,None

In [10]:
df_global[['Position 2', 'Position 3']] = df_global['Other Positions'].str.split(expand=True)

In [11]:
df_global.tail()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Main Position,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3
9228,NaN,Kian Le Fondre,Centre-Forward,"Feb 2, 2005",19,"Scotland, England",England,Stockport,NaN,-,Striker,RW LW,Scotland,England,RW,LW
9229,NaN,Tobi Adeyemo,Centre-Forward,"Mar 14, 2005",19,"England, Nigeria",England,London,NaN,-,Striker,NaN,England,Nigeria,NaN,NaN
9230,64.0,Sonny Finch,Centre-Forward,"Aug 5, 2005",18,England,England,Sunderland,NaN,-,Striker,SS,England,None,SS,None
9231,14.0,Dajaune Brown,Centre-Forward,"Oct 16, 2005",18,"Jamaica, England",England,Nottingham,NaN,-,Striker,NaN,Jamaica,England,NaN,NaN
9232,22.0,Emre Tezgel,Centre-Forward,"Sep 19, 2005",18,"Türkiye, England",England,Burton,"1,82",-,Striker,NaN,Türkiye,England,NaN,NaN

## Remove parenthesis in place of Birth

In [12]:

#strt_pos = df_global['Place of Birth'].values[0].find("(")
#stop_pos = df_global['Place of Birth'].values[0].find(")")

#if (strt_pos == -1) and (stop_pos == -1) : 
    #i = i+1
    #print(strt_pos)
    #print(stop_pos)
    #print(df_global['Place of Birth'].values[0])
#else:
    #df_global['Place of Birth'].values[0] = f"{df_global['Place of Birth'].values[7][:strt_pos:].strip()} {df_global['Place of Birth'].values[7][stop_pos+1:].strip()}"
    #print("oui")
    #print(df_global['Place of Birth'].values[7])

In [13]:
for i in range(len(df_global)):
    if type(df_global['Place of Birth'].values[i]) is str :
        strt_pos = df_global['Place of Birth'].values[i].find('(')
        stop_pos = df_global['Place of Birth'].values[i].find(')')
        if (strt_pos == -1) and (stop_pos == -1) : 
            i+1
        else:
            df_global['Place of Birth'].values[i] = f"{df_global['Place of Birth'].values[i][:strt_pos:].strip()} {df_global['Place of Birth'].values[i][stop_pos+1:].strip()}"
            i+1
            df_global['Place of Birth'].values[i] = df_global['Place of Birth'].values[i][:-1]
    else: 
        i+1

## Remove text after comma

In [14]:
for i in range(len(df_global)):
    if type(df_global['Place of Birth'].values[i]) is str :
        df_global['Place of Birth'].values[i] = df_global['Place of Birth'].values[i].split(",")[0]
    else: 
        i+1

## Remove accents on birthplaces

In [15]:
import unicodedata

for i in range(len(df_global)):
    if type(df_global['Place of Birth'].values[i]) is str :
        n= unicodedata.normalize('NFKD', df_global['Place of Birth'].values[i])
        df_global['Place of Birth'].values[i] = ''.join([c for c in n if not unicodedata.combining(c)]) 
    else: 
        i+1

In [16]:
with pd.option_context('display.max_rows',None, 'display.max_columns',None):print(df_global)

      Number                                Name            Position
0       33.0                        Scott Carson          Goalkeeper  \
1        NaN                        Luke McShane          Goalkeeper
2        NaN                         Jacob Giles          Goalkeeper
3        NaN                          Greg Smith          Goalkeeper
4        NaN                           Tim Deasy          Goalkeeper
5        NaN                   Craig Summersgill          Goalkeeper
6        NaN                       James Spencer          Goalkeeper
7        1.0                          Chris Neal          Goalkeeper
8       21.0                       Steven Drench          Goalkeeper
9        NaN                          Dean Brill          Goalkeeper
10       NaN                        Michael Poke          Goalkeeper
11       NaN                       James Debbage          Goalkeeper
12       NaN                        Lance Cronin          Goalkeeper
13       NaN                        Andy Jeffery          Goalkeeper
14       NaN                        Ashley Timms          Goalkeeper
15       NaN                       Ryan Harrison          Goalkeeper
16       NaN                        James Coates          Goalkeeper
17       NaN                        Dean Coleman          Goalkeeper
18      13.0                     David Stockdale          Goalkeeper
19       NaN                         Andrew Hogg          Goalkeeper
20       NaN                         Dean Gerken          Goalkeeper
21       NaN                           Jake Cole          Goalkeeper
22       NaN                       Ross Turnbull          Goalkeeper
23       NaN                         Scott Brown          Goalkeeper
24       NaN                    Stuart Tomlinson          Goalkeeper
25       NaN                          Adam Ogden          Goalkeeper
26      22.0                          Tom Heaton          Goalkeeper
27       1.0                       Adam Legzdins          Goalkeeper
28      13.0                      Scott Flinders          Goalkeeper
29       NaN                          Tom Fawdry          Goalkeeper
30       NaN                        Aaran Taylor          Goalkeeper
31       NaN                        Dan Haystead          Goalkeeper
32       NaN                      Simon Overland          Goalkeeper
33       NaN                       Danny Knowles          Goalkeeper
34       NaN                          Syed Adney          Goalkeeper
35       NaN                         Jamie Waite          Goalkeeper
36       NaN                       Adam Bartlett          Goalkeeper
37       NaN                        Dale Roberts          Goalkeeper
38       NaN                           Joe Anyon          Goalkeeper
39      21.0                          John Ruddy          Goalkeeper
40      21.0                         Mark Howard          Goalkeeper
41       NaN                          Rory Grand          Goalkeeper
42       NaN              Scott Chalmers-Stevens          Goalkeeper
43       NaN                         Matt Bulman          Goalkeeper
44       NaN                          Matt Jones          Goalkeeper
45       NaN                         Martin Rice          Goalkeeper
46       NaN                          Sam Ashton          Goalkeeper
47       NaN                     Phil Palethorpe          Goalkeeper
48       NaN                      Tommy Forecast          Goalkeeper
49       NaN                           Tommy Lee          Goalkeeper
50       NaN                           Ben Smith          Goalkeeper
51       NaN                      Martin Horsell          Goalkeeper
52       NaN                       Darren Behcet          Goalkeeper
53       NaN                       Chris Howarth          Goalkeeper
54       NaN                          Orkan Avci          Goalkeeper
55       NaN                          Carl Ikeme          Goalkeeper
56       1.0                          Paul Jones          Goalkeeper
57       NaN                        Lee Robinson          Goalkeeper
58      37.0                          Rob Elliot          Goalkeeper
59       NaN                      Michael Jordan          Goalkeeper
60       1.0                        Chris Wright          Goalkeeper
61      25.0                        David Martin          Goalkeeper
62       1.0                            Joe Hart          Goalkeeper
63      26.0                           Ben Hamer          Goalkeeper
64       NaN                      Marcus Garnham          Goalkeeper
65       NaN                       Tom Nicholson          Goalkeeper
66       NaN                     Ryan Brookfield          Goalkeeper
67       NaN                        Ashlee Jones          Goalkeeper
68       NaN                      Richard Martin          Goalkeeper
69       NaN                        Scott Davies          Goalkeeper
70       NaN                          Dan Barker          Goalkeeper
71       NaN                       Clark Masters          Goalkeeper
72       NaN                          Lewis Edge          Goalkeeper
73       NaN                    Mark Wilberforce          Goalkeeper
74       1.0                        Mark Cousins          Goalkeeper
75       NaN                           Joe Lewis          Goalkeeper
76      12.0                         Josh Lillis          Goalkeeper
77       NaN                          Toby Spain          Goalkeeper
78       NaN                          Karl Wills          Goalkeeper
79       NaN                          Aaron Howe          Goalkeeper
80       NaN                          Ian Deakin          Goalkeeper
81      13.0                       Michael Jones          Goalkeeper
82       NaN                       Curtis Aspden          Goalkeeper
83       NaN                          Chris Dunn          Goalkeeper
84       NaN                          Will Puddy          Goalkeeper
85       NaN                         Jack Norton          Goalkeeper
86       NaN                       James Russell          Goalkeeper
87       NaN                        David Knight          Goalkeeper
88       NaN                      Paul Lancaster          Goalkeeper
89       NaN                         Ben Alnwick          Goalkeeper
90      20.0                      Fraser Forster          Goalkeeper
91       1.0                      Ben Hinchliffe          Goalkeeper
92       1.0                   Richard O'Donnell          Goalkeeper
93      13.0                         Scott Loach          Goalkeeper
94       NaN                     Jason Alexander          Goalkeeper
95       NaN                        Tony Breeden          Goalkeeper
96       NaN                       Andy Rafferty          Goalkeeper
97       NaN                     Chris Lewington          Goalkeeper
98       NaN                            Sam Mott          Goalkeeper
99       NaN                     Nick Liversedge          Goalkeeper
100      NaN                 Corrin Brooks-Meade          Goalkeeper
101      NaN                       Martin Fearon          Goalkeeper
102      NaN                         Lee Butcher          Goalkeeper
103     34.0                      Frank Fielding          Goalkeeper
104      1.0                        Luke Daniels          Goalkeeper
105      1.0                        Sam Slocombe          Goalkeeper
106      NaN                    Stephen Hollyoak          Goalkeeper
107      NaN                         Sam Beasant          Goalkeeper
108      NaN                          Dan Lowson          Goalkeeper
109      NaN                        Dave Roberts          Goalkeeper
110      NaN                      Jonathan Hedge          Goalkeeper
111      NaN                     Cameron Belford          Goalkeeper
112      NaN                           Mark Cook          Goalkeeper
113      NaN                     Chris Winterton          Goalkeeper
114      NaN                       John Sullivan          Goalkeeper
115      NaN                      Jamie Annerson          Goalkeeper
116      NaN                        Paddy Gamble          Goalkeeper
117      NaN                           Zak Jones          Goalkeeper
118      NaN                         Rikki Banks          Goalkeeper
119      NaN                       Jonathan Lund          Goalkeeper
120      NaN                           Joe Welch          Goalkeeper
121      1.0                       Alex McCarthy          Goalkeeper
122     32.0                         Jamie Jones          Goalkeeper
123      1.0                         Rob Lainton          Goalkeeper
124     25.0                        Steve Arnold          Goalkeeper
125      NaN                        Ash Malhotra          Goalkeeper
126      NaN                       James Beasant          Goalkeeper
127      NaN                     Ross Kitteridge          Goalkeeper
128     21.0                       Matthew Upton          Goalkeeper
129      NaN                      Shane McWeeney          Goalkeeper
130      1.0                       Laurie Walker          Goalkeeper
131      NaN                          Josh Mimms          Goalkeeper
132      NaN                       Arron Jameson          Goalkeeper
133      NaN                       Matt Sargeant          Goalkeeper
134      1.0                        David Button          Goalkeeper
135      1.0                         Paul Farman          Goalkeeper
136     13.0                      Simon Eastwood          Goalkeeper
137      NaN                     David Blackmore          Goalkeeper
138      NaN                       Neill Collett          Goalkeeper
139      NaN                        Craig Vernon          Goalkeeper
140      NaN                 Matt Armstrong-Ford          Goalkeeper
141      NaN                        Billy Lumley          Goalkeeper
142      NaN                         Nick Jordan          Goalkeeper
143      NaN                   Andreas Arestidou          Goalkeeper
144      1.0                         Ross Worner          Goalkeeper
145      NaN                          Dave Hogan          Goalkeeper
146      NaN                    Callum Hawthorne          Goalkeeper
147      NaN                         Ross Atkins          Goalkeeper
148      NaN                        Carl Pentney          Goalkeeper
149      NaN                     Preston Edwards          Goalkeeper
150      NaN                         Jon Stewart          Goalkeeper
151      NaN                       James McKeown          Goalkeeper
152      NaN                     Tim Sandercombe          Goalkeeper
153      NaN                          Mike Green          Goalkeeper
154      NaN                           Seb Brown          Goalkeeper
155      NaN                      Andrew Plummer          Goalkeeper
156     23.0                        Jason Steele          Goalkeeper
157      1.0                      Neil Etheridge          Goalkeeper
158      NaN                       Elliot Parish          Goalkeeper
159     21.0                             Joe Day          Goalkeeper
160     33.0                          Gary Woods          Goalkeeper
161      NaN                          Jack Baker          Goalkeeper
162      NaN                       Michael Emery          Goalkeeper
163      NaN                       Aaron Chapman          Goalkeeper
164      NaN                   Brentton Muhammad          Goalkeeper
165      NaN                       Danny Roberts          Goalkeeper
166      NaN                           Paul Hunt          Goalkeeper
167      NaN                        Thomas Flynn          Goalkeeper
168      NaN                      Phil Carpenter          Goalkeeper
169     28.0                         Karl Darlow          Goalkeeper
170      1.0                         Simon Moore          Goalkeeper
171     31.0                       James Belshaw          Goalkeeper
172     12.0                            Ben Amos          Goalkeeper
173      1.0                          Mark Oxley          Goalkeeper
174      NaN                       Erbil Bozkurt          Goalkeeper
175      NaN                        Greg Hartley          Goalkeeper
176      1.0                      Elliot Justham          Goalkeeper
177     13.0                          Craig Ross          Goalkeeper
178      NaN                       Jack Cudworth          Goalkeeper
179      NaN                    Josh Ollerenshaw          Goalkeeper
180      1.0                           Jas Singh          Goalkeeper
181      1.0                       Mark Halstead          Goalkeeper
182      1.0                      Nathan Ashmore          Goalkeeper
183      NaN                       Matty Edwards          Goalkeeper
184      NaN                        Lloyd Saxton          Goalkeeper
185      NaN                       Leigh Overton          Goalkeeper
186      NaN                         Conor Grant          Goalkeeper
187      NaN                       Alex Smithies          Goalkeeper
188      NaN                      Lloyd Anderson          Goalkeeper
189      NaN          Danzelle St Louis-Hamilton          Goalkeeper
190      NaN                          Sam Filler          Goalkeeper
191      NaN                   Scott Pocklington          Goalkeeper
192      NaN                       Martin Hunter          Goalkeeper
193      NaN                        Chris Martin          Goalkeeper
194     18.0                     Wes Foderingham          Goalkeeper
195      1.0                          James Shea          Goalkeeper
196      NaN                       Jason Astbury          Goalkeeper
197      NaN                       Lamar Johnson          Goalkeeper
198      NaN                        Niall Cooper          Goalkeeper
199      NaN                         Phil Draper          Goalkeeper
200      NaN                       Ross McMullan          Goalkeeper
201      NaN                         Ben Chapman          Goalkeeper
202      NaN                       Rhett Heister          Goalkeeper
203      NaN                         Max Johnson          Goalkeeper
204      NaN                    Ritchie Branagan          Goalkeeper
205      NaN                         Simon Locke          Goalkeeper
206      NaN                        Lewis Graham          Goalkeeper
207      1.0                          Sam Walker          Goalkeeper
208      NaN                        Matthew Ince          Goalkeeper
209      NaN                         Alex Street          Goalkeeper
210      NaN                       James Kendall          Goalkeeper
211      NaN                        Daniel Platt          Goalkeeper
212      NaN                    Nicholas Greaves          Goalkeeper
213      NaN                       Deren Ibrahim          Goalkeeper
214      NaN                     Nathan McDonald          Goalkeeper
215      NaN                         Hakan Duyan          Goalkeeper
216      NaN                          Jack Binks          Goalkeeper
217      NaN                       Aaron Butcher          Goalkeeper
218      NaN                        James Severn          Goalkeeper
219      NaN                        Liam O'Brien          Goalkeeper
220      NaN                          Dan Thomas          Goalkeeper
221      NaN                 JJ Banasco-Zaragoza          Goalkeeper
222      NaN                 Daniel Lloyd-Weston          Goalkeeper
223      NaN                           Jake Kean          Goalkeeper
224      NaN                        Josh Pelling          Goalkeeper
225      NaN                     Niki-Lee Bulmer          Goalkeeper
226      NaN                         Declan Rudd          Goalkeeper
227      NaN                          Mark Scott          Goalkeeper
228      NaN                       Grant Shenton          Goalkeeper
229      NaN                        Mitch Walker          Goalkeeper
230     13.0                Christopher Oldfield          Goalkeeper
231      NaN                       Joe Collister          Goalkeeper
232      NaN                      Jonathan North          Goalkeeper
233     30.0                         Dean Lyness          Goalkeeper
234      1.0                       Alex Mitchell          Goalkeeper
235      NaN                      Simon Williams          Goalkeeper
236     22.0                           Nick Pope          Goalkeeper
237     17.0                         Ryan Allsop          Goalkeeper
238     13.0                          Ben Wilson          Goalkeeper
239     29.0                      Mark Gillespie          Goalkeeper
240     21.0                          Adam Smith          Goalkeeper
241     30.0                        Adam Stevens          Goalkeeper
242      NaN                         Simon Grant          Goalkeeper
243      1.0                        Jack Harding          Goalkeeper
244      NaN                      Alex Tokarczyk          Goalkeeper
245      NaN                        Ben Woodhead          Goalkeeper
246      NaN                            Rob Peet          Goalkeeper
247      NaN                       Matthew Crook          Goalkeeper
248      NaN                         Adam McHugh          Goalkeeper
249     13.0                   Marcus Bettinelli          Goalkeeper
250      1.0                        Lee Nicholls          Goalkeeper
251     21.0                           Jed Steer          Goalkeeper
252      1.0                      Freddie Toomer          Goalkeeper
253      1.0                        Deniz Mehmet          Goalkeeper
254      NaN                     Lewis Gwilliams          Goalkeeper
255      NaN                        Luke Cairney          Goalkeeper
256      NaN                  Michael Ballantyne          Goalkeeper
257      NaN                 Cameron Baker-Owers          Goalkeeper
258      NaN                        Stuart Dixon          Goalkeeper
259      NaN                        Denham Hinds          Goalkeeper
260      NaN                          Jack Dovey          Goalkeeper
261      NaN                       Liam Mitchell          Goalkeeper
262      NaN                        Louis Connor          Goalkeeper
263      1.0                         Sam Johnson          Goalkeeper
264      NaN                       Chris Elliott          Goalkeeper
265      NaN                      Dominic Comrie          Goalkeeper
266      NaN                           Sean Cuff          Goalkeeper
267      NaN                        Charlie Mann          Goalkeeper
268      NaN                   Deale Chamberlain          Goalkeeper
269      1.0                         Jack Turner          Goalkeeper
270      NaN                          Tim Cooney          Goalkeeper
271      NaN                          Sam Cowler          Goalkeeper
272      NaN                     Michael Bertram          Goalkeeper
273      NaN                         Tom Coulton          Goalkeeper
274      NaN                          Conor Winn          Goalkeeper
275      NaN                       Nick Thompson          Goalkeeper
276      NaN                     Ollie Chenoweth          Goalkeeper
277      NaN                      Jordan Tebbutt          Goalkeeper
278      NaN                          Ryan Jones          Goalkeeper
279      1.0                        Jack Giddens          Goalkeeper
280      NaN                         Dave Parton          Goalkeeper
281      NaN                        Jamie Butler          Goalkeeper
282      1.0                       Sam Johnstone          Goalkeeper
283     25.0                      Daniel Bentley          Goalkeeper
284      NaN                       Jonathan Bond          Goalkeeper
285     12.0                         George Long          Goalkeeper
286      1.0                         Will Norris          Goalkeeper
287     13.0                           Jay Lynch          Goalkeeper

In [17]:
df_global.to_csv("../../data/england/england_clean.csv", header= True, index=False, encoding="utf-8")