# Transfermarkt scrapping with Beautiful Soup & Selenium

## Imports

In [1]:
import re
import requests
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

## Webdriver options

In [2]:
options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
options.add_argument('--incognito')
#options.add_argument('--headless')

driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)
driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/1")

/var/folders/qw/qjxyt3tn1057c6j4pl5tb03c0000gn/T/ipykernel_59427/2000119249.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)

## Create dataframes and scrap the data from Transfermarkt

In [3]:
df_1985 = pd.DataFrame()
df_1986 = pd.DataFrame()
df_1987 = pd.DataFrame()
df_1988 = pd.DataFrame()
df_1989 = pd.DataFrame()
df_1990 = pd.DataFrame()
df_1991 = pd.DataFrame()
df_1992 = pd.DataFrame()
df_1993 = pd.DataFrame()
df_1994 = pd.DataFrame()
df_1995 = pd.DataFrame()
df_1996 = pd.DataFrame()
df_1997 = pd.DataFrame()
df_1998 = pd.DataFrame()
df_1999 = pd.DataFrame()
df_2000 = pd.DataFrame()
df_2001 = pd.DataFrame()
df_2002 = pd.DataFrame()
df_2003 = pd.DataFrame()
df_2004 = pd.DataFrame()
df_2005 = pd.DataFrame()

In [179]:
#driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/1")
page_source = driver.page_source
rows = []
next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
count = 2

#print(len(next_buttons))

#for x in range(len(next_buttons)):
while (len(next_buttons)!=0) :
    
    if next_buttons[0].is_displayed():

        soup = BeautifulSoup(page_source, "html.parser")
        #next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        tables = soup.find_all('table')
        table = soup.find('table', class_ = 'items')  
      
        #Collect data for odd rows  
        for row in table.tbody.find_all('tr', class_="odd"):    
        # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Main Position': "Striker",
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Portugal',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
            } )

        #Collect data for even rows
        for row in table.tbody.find_all('tr', class_="even"):    
        # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Main Position': "Striker",
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Portugal',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
            } )        

        driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/" + "" + str(count))
        page_source = driver.page_source
        next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        count +=1


page_source = driver.page_source
soup = BeautifulSoup(page_source, "html.parser")
tables = soup.find_all('table')
table = soup.find('table', class_ = 'items')  
      
#Collect data for odd rows        
for row in table.tbody.find_all('tr', class_="odd"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Main Position': "Striker",
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Portugal',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
    } )

#Collect data for even rows
for row in table.tbody.find_all('tr', class_="even"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Main Position': "Striker",
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Portugal',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
    } )  

df_2005 = pd.DataFrame(rows)               
df_2005

,Number,Name,Main Position,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Other Positions,Height,Market Value
0,,Rodrigo Ribeiro,Striker,Centre-Forward,"Apr 28, 2005",19,[Portugal],Portugal,Viana do Castelo,SS RW,"1,85",€3.00m
1,89,Gustavo Varela,Striker,Centre-Forward,"Jan 30, 2005",19,[Portugal],Portugal,Lisboa,,"1,84",€500k
2,21,Grave,Striker,Centre-Forward,"Oct 27, 2005",18,[Portugal],Portugal,Santa Maria da Feira,,,€150k
3,,António Indami,Striker,Centre-Forward,"Jun 11, 2005",19,[Portugal],Portugal,,,"1,74",-
4,9,Daniel Patrocínio,Striker,Centre-Forward,"Jun 4, 2005",19,[Portugal],Portugal,,,,-
5,,Duarte Carreira,Striker,Centre-Forward,"Apr 15, 2005",19,[Portugal],Portugal,,,"1,97",-
6,79,Ricardo Ferreira,Striker,Centre-Forward,"Dec 10, 2005",18,[Portugal],Portugal,,RW LW,,-
7,,Rodrigo Malheiros,Striker,Centre-Forward,"Apr 13, 2005",19,[Portugal],Portugal,Vila Nova de Gaia,,"1,76",-
8,91,Rudi Almeida,Striker,Centre-Forward,"Mar 19, 2005",19,[Portugal],Portugal,Fátima,,"1,85",-
9,,Iuri Borges,Striker,Centre-Forward,"Feb 15, 2005",19,[Portugal],Portugal,,,"1,88",-
10,,Matheus Monteiro dos Santos,Striker,Centre-Forward,"Oct 9, 2005",18,"[Portugal, Brazil]",Portugal,Matosinhos,SS AM,"1,89",-
11,,Thiago Figueiredo,Striker,Centre-Forward,"Nov 29, 2005",18,"[Portugal, Brazil]",Portugal,,,"1,80",-
12,97,Dinis Rodrigues,Striker,Centre-Forward,"Jul 14, 2005",18,[Portugal],Portugal,Maia,,"1,87",€700k
13,17,Brandão,Striker,Centre-Forward,"Aug 7, 2005",18,[Portugal],Portugal,Oliveira de Azeméis,,,€200k
14,33,Adulai Djabi Embalo,Striker,Centre-Forward,"Jun 30, 2005",19,"[Luxembourg, Portugal]",Portugal,,,"1,88",€125k
15,27,Sassá,Striker,Centre-Forward,"Feb 6, 2005",19,[Portugal],Portugal,Ponte da Barca,,"1,74",-
16,,Pedro Cauã Gomes,Striker,Centre-Forward,"Jun 14, 2005",19,"[Portugal, Brazil]",Portugal,Gafanha de Nazaré,SS,"1,80",-
17,18,Tomás Afonso,Striker,Centre-Forward,"Nov 13, 2005",18,[Portugal],Portugal,Lissabon,,"1,89",-
18,,João Bernardo,Striker,Centre-Forward,"Jan 21, 2005",19,[Portugal],Portugal,Anadia,,"1,83",-
19,96,Gonçalo Próspero,Striker,Centre-Forward,"Jun 1, 2005",19,[Portugal],Portugal,Olhão,,,-
20,86,Rafael Nel,Striker,Centre-Forward,"Apr 3, 2005",19,[Portugal],Portugal,Amadora,AM RW,"1,82",-
21,59,Leonardo Oliveira,Striker,Centre-Forward,"Feb 8, 2005",19,"[Sweden, Portugal]",Portugal,Porto,SS,"1,87",-
22,,João Costa,Striker,Centre-Forward,"Mar 12, 2005",19,[Portugal],Portugal,Lagos,,,-
23,,Carlos Durães,Striker,Centre-Forward,"Mar 15, 2005",19,[Portugal],Portugal,Vila Nova de Famalicão,,"1,78",-

In [114]:
with pd.option_context('display.max_rows',None, 'display.max_columns',None):print(df_2002)

   Number              Name Main Position     Position  Date of Birth Age
0      33      João Marques       Striker  Left Winger  Feb 13, 2002   22  \
1      52  Henrique Pereira       Striker  Left Winger  Feb 15, 2002   22
2      87              Jota       Striker  Left Winger  Jul 22, 2002   21
3      99      Pedro Vieira       Striker  Left Winger   May 3, 2002   21
4       7    Rafael Quirino       Striker  Left Winger   Nov 8, 2002   21
5      15     Afonso Gaspar       Striker  Left Winger  Mar 13, 2002   22
6                Alex Lopes       Striker  Left Winger  Feb 23, 2002   22
7      49       Kevin Silva       Striker  Left Winger  Mar 10, 2002   22
8               André Forte       Striker  Left Winger  Jul 20, 2002   21
9      80     Tiago Ventura       Striker  Left Winger  Jun 19, 2002   21
10     11     Dilan Pussick       Striker  Left Winger  Sep 13, 2002   21
11                Rui Jorge       Striker  Left Winger   Mar 3, 2002   22
12     11      Hugo Ribeiro       Striker  Left Winger  Apr 25, 2002   21
13     77      Hélio Varela       Striker  Left Winger   May 3, 2002   21
14     79  Afonso Rodrigues       Striker  Left Winger  Aug 19, 2002   21
15     10              Jota       Striker  Left Winger   Sep 6, 2002   21
16     10    Bruno Ferreira       Striker  Left Winger  Aug 22, 2002   21
17          Adriano Biguane       Striker  Left Winger  Mar 29, 2002   22
18     10              Kiku       Striker  Left Winger  Jul 25, 2002   21
19     31      David Rebelo       Striker  Left Winger  Nov 13, 2002   21
20     19              Pipo       Striker  Left Winger  Jan 17, 2002   22
21     16  Afonso Vagarinho       Striker  Left Winger   Jul 4, 2002   21
22     17       João Varela       Striker  Left Winger  Jan 12, 2002   22
23     75    Carlos Almeida       Striker  Left Winger  Apr 22, 2002   22
24     11        Hugo Neves       Striker  Left Winger   Dec 3, 2002   21

                  Nationality Birth Country   Place of Birth Other Positions
0                  [Portugal]      Portugal         Barreiro         AM   RW  \
1                  [Portugal]      Portugal           Lisboa              RW
2                  [Portugal]      Portugal        Guimarães              RW
3                  [Portugal]      Portugal             Beja         RW   CF
4                  [Portugal]      Portugal                               CF
5                  [Portugal]      Portugal            Sertã              AM
6                  [Portugal]      Portugal                               RW
7      [Portugal, Cape Verde]      Portugal           Lisboa         CF   RW
8                  [Portugal]      Portugal  Figueira da Foz         RW   SS
9                  [Portugal]      Portugal         Gondomar         CF   SS
10  [Portugal, Guinea-Bissau]      Portugal           Lisboa              RW
11                 [Portugal]      Portugal                          LM   LB
12                 [Portugal]      Portugal         Penafiel              RW
13     [Cape Verde, Portugal]      Portugal           Almada         AM   RW
14                 [Portugal]      Portugal            Braga         RW   SS
15                 [Portugal]      Portugal           Aveiro         CF   RW
16                 [Portugal]      Portugal      Santo Tirso              RW
17     [Portugal, Cape Verde]      Portugal                               RW
18                 [Portugal]      Portugal        Mangualde              RW
19                 [Portugal]      Portugal          Coimbra         AM   RW
20                 [Portugal]      Portugal       Matosinhos         AM   LB
21                 [Portugal]      Portugal         Santarém              RW
22                 [Portugal]      Portugal                               RW
23                 [Portugal]      Portugal          Funchal         RW   LM
24                 [Portugal]      Portugal                          SS   CF

   Height Market Value
0    1,79       €3.50m
1    1,78       €2.00m
2    1,76        €200k
3    1,90        €125k
4    1,87            -
5    1,75            -
6                    -
7    1,89            -
8                    -
9    1,75            -
10   1,82            -
11   1,68            -
12   1,76            -
13   1,76       €2.50m
14   1,78        €200k
15   1,85        €125k
16   1,80            -
17   1,73            -
18   1,79            -
19   1,80            -
20   1,78            -
21   1,69            -
22   1,70            -
23   1,70            -
24   1,76            -

## Merge all the dataframes into a single one and save the df into a csv file

In [180]:
df_merged = pd.concat([df_1985,df_1986,df_1987,df_1988,df_1989,df_1990,df_1991,df_1992,df_1993,df_1994,df_1995,df_1996,df_1997,df_1998,df_1999,df_2000,df_2001,df_2002,df_2003,df_2004,df_2005],ignore_index=True)

In [181]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630 entries, 0 to 629
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           630 non-null    object
 1   Name             630 non-null    object
 2   Main Position    630 non-null    object
 3   Position         630 non-null    object
 4   Date of Birth    630 non-null    object
 5   Age              630 non-null    object
 6   Nationality      630 non-null    object
 7   Birth Country    630 non-null    object
 8   Place of Birth   630 non-null    object
 9   Other Positions  630 non-null    object
 10  Height           630 non-null    object
 11  Market Value     630 non-null    object
dtypes: object(12)
memory usage: 59.2+ KB

In [182]:
df_merged.to_csv("../../data/portugal/portugal_centerforwards.csv", header= True, index=False)