# Transfermarkt scrapping with Beautiful Soup & Selenium

## Imports

In [1]:
import re
import requests
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

## Webdriver options

In [196]:
options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
#options.add_argument('--incognito')
#options.add_argument('--headless')

driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)
driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/1")

/var/folders/qw/qjxyt3tn1057c6j4pl5tb03c0000gn/T/ipykernel_24470/2194472983.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)

## Create dataframes and scrap the data from Transfermarkt

In [3]:
df_1985 = pd.DataFrame()
df_1986 = pd.DataFrame()
df_1987 = pd.DataFrame()
df_1988 = pd.DataFrame()
df_1989 = pd.DataFrame()
df_1990 = pd.DataFrame()
df_1991 = pd.DataFrame()
df_1992 = pd.DataFrame()
df_1993 = pd.DataFrame()
df_1994 = pd.DataFrame()
df_1995 = pd.DataFrame()
df_1996 = pd.DataFrame()
df_1997 = pd.DataFrame()
df_1998 = pd.DataFrame()
df_1999 = pd.DataFrame()
df_2000 = pd.DataFrame()
df_2001 = pd.DataFrame()
df_2002 = pd.DataFrame()
df_2003 = pd.DataFrame()
df_2004 = pd.DataFrame()
df_2005 = pd.DataFrame()

In [205]:
#driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/1")
page_source = driver.page_source
rows = []
next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
count = 2

#print(len(next_buttons))

#for x in range(len(next_buttons)):
while (len(next_buttons)!=0) :
    
    if next_buttons[0].is_displayed():

        soup = BeautifulSoup(page_source, "html.parser")
        #next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        tables = soup.find_all('table')
        table = soup.find('table', class_ = 'items')  
      
        #Collect data for odd rows  
        for row in table.tbody.find_all('tr', class_="odd"):    
        # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Main Position': "Striker",
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Spain',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
            } )

        #Collect data for even rows
        for row in table.tbody.find_all('tr', class_="even"):    
        # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Main Position': "Striker",
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Spain',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
            } )        

        driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/" + "" + str(count))
        page_source = driver.page_source
        next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        count +=1


page_source = driver.page_source
soup = BeautifulSoup(page_source, "html.parser")
tables = soup.find_all('table')
table = soup.find('table', class_ = 'items')  
      
#Collect data for odd rows        
for row in table.tbody.find_all('tr', class_="odd"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Main Position': "Striker",
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Spain',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
    } )

#Collect data for even rows
for row in table.tbody.find_all('tr', class_="even"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Main Position': "Striker",
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Spain',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
    } )  

df_2005 = pd.DataFrame(rows)               
df_2005

,Number,Name,Main Position,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Other Positions,Height,Market Value
0,33,Adrián Liso,Striker,Left Winger,"Apr 2, 2005",19,[Spain],Spain,Zaragoza,CF,"1,82",€600k
1,20,Arkaitz Mariezkurrena,Striker,Left Winger,"Apr 5, 2005",19,[Spain],Spain,Astigarraga,,,€200k
2,24,Adrian Caragea,Striker,Left Winger,"Sep 7, 2005",19,[Romania],Spain,Jaen,RW,"1,82",€100k
3,17,Darío Ramírez,Striker,Left Winger,"Jan 14, 2005",19,[Spain],Spain,Haría (Las Palmas),RW,,€50k
4,,Pablo Évora,Striker,Left Winger,"Jan 8, 2005",19,[Spain],Spain,Huelva,RW AM,,-
5,11,Dani Rodríguez,Striker,Left Winger,"Apr 29, 2005",19,[Spain],Spain,Palencia,RW CF,"1,76",-
6,,Javi Urra,Striker,Left Winger,"Jun 27, 2005",19,[Spain],Spain,Valencia,AM,"1,80",-
7,,Daniel Prisacaru,Striker,Left Winger,"Feb 4, 2005",19,"[Moldova, Romania]",Spain,Madrid,,"1,66",-
8,,Marcos Aceituno,Striker,Left Winger,"May 25, 2005",19,[Spain],Spain,Talavera de la Reina,,,-
9,17,George Andrews,Striker,Left Winger,"Mar 2, 2005",19,"[Spain, England]",Spain,Palma de Mallorca,RW CF,"1,87",-
10,20,Rayane Belaid,Striker,Left Winger,"Nov 2, 2005",18,"[Spain, Algeria]",Spain,Orihuela,RW SS,"1,78",-
11,,Iván Salguero,Striker,Left Winger,"Jan 7, 2005",19,[Spain],Spain,,,,-
12,,Marc Rodríguez,Striker,Left Winger,"Jul 30, 2005",19,[Spain],Spain,,,,-
13,17,Jesús Rodriguez,Striker,Left Winger,"Nov 21, 2005",18,[Spain],Spain,Sevilla,,"1,85",€500k
14,7,Dani Rodríguez,Striker,Left Winger,"Aug 9, 2005",19,[Spain],Spain,Astigarraga,RW CM,"1,70",€100k
15,11,Yassin Tallal,Striker,Left Winger,"Mar 3, 2005",19,"[Morocco, Spain]",Spain,Madrid,SS RW,"1,73",€50k
16,22,Gasolina,Striker,Left Winger,"Oct 28, 2005",18,[Spain],Spain,Navalmoral de la Mata,,,-
17,11,Aritz Conde,Striker,Left Winger,"Oct 14, 2005",18,[Spain],Spain,Donostia-San Sebastián,RW,"1,78",-
18,,Quim Montenegro,Striker,Left Winger,"Mar 25, 2005",19,[Spain],Spain,,,,-
19,,Christian Membrives,Striker,Left Winger,"Aug 19, 2005",19,"[Spain, Dominican Republic]",Spain,Valencia,RW,"1,73",-
20,8,Pablo Lomas,Striker,Left Winger,"Apr 14, 2005",19,[Spain],Spain,Santander,RW,"1,76",-
21,20,Adnane Bensaad,Striker,Left Winger,"Oct 21, 2005",18,"[Morocco, Spain]",Spain,Murcia,CF RW,"1,80",-
22,7,Hugo Guzón,Striker,Left Winger,"Apr 16, 2005",19,[Spain],Spain,Valladolid,AM,"1,65",-
23,27,Joel Roca,Striker,Left Winger,"Jun 7, 2005",19,[Spain],Spain,Camprodón,AM RW,"1,76",-
24,,Alex Cid,Striker,Left Winger,"Jan 11, 2005",19,[Spain],Spain,Ourense,,,-

In [198]:
with pd.option_context('display.max_rows',None, 'display.max_columns',None):print(df_2001)

   Number                  Name Main Position     Position  Date of Birth Age
0      16            Álex Baena       Striker  Left Winger  Jul 20, 2001   23  \
1      20             Bryan Gil       Striker  Left Winger  Feb 11, 2001   23
2      24        Víctor Mollejo       Striker  Left Winger  Jan 21, 2001   23
3      11          Kevin Medina       Striker  Left Winger  Feb 26, 2001   23
4      10         Álvaro Martín       Striker  Left Winger  Jan 15, 2001   23
5      11          Miguel Puche       Striker  Left Winger  Apr 30, 2001   23
6      17            Javi López       Striker  Left Winger   May 5, 2001   23
7      19         Kenneth Soler       Striker  Left Winger  Feb 16, 2001   23
8      21         Jorge Padilla       Striker  Left Winger  Apr 23, 2001   23
9       7         Miquel Alorda       Striker  Left Winger  Jun 13, 2001   23
10     18        Asier Teijeira       Striker  Left Winger  Oct 10, 2001   22
11                  Adri Ferrer       Striker  Left Winger  Feb 12, 2001   23
12     18     Ayoub El Battioui       Striker  Left Winger   Apr 2, 2001   23
13      7     Ander Barrenetxea       Striker  Left Winger  Dec 27, 2001   22
14     19        Bryan Zaragoza       Striker  Left Winger   Sep 9, 2001   23
15      7           Borja Sainz       Striker  Left Winger  Feb 21, 2001   23
16     11         Diego Collado       Striker  Left Winger   Jan 9, 2001   23
17     19           Arnau Ortiz       Striker  Left Winger  Oct 29, 2001   22
18     11           Marco Camus       Striker  Left Winger  Nov 16, 2001   22
19     22            Unai Buján       Striker  Left Winger   Feb 8, 2001   23
20     21       Carlos Mattheus       Striker  Left Winger  Oct 25, 2001   22
21     14        Mario da Costa       Striker  Left Winger  May 14, 2001   23
22      7          Tiko Iniesta       Striker  Left Winger   Jun 7, 2001   23
23      7            Samu Pérez       Striker  Left Winger  Jun 10, 2001   23
24     18        Adrián Garrido       Striker  Left Winger  Nov 18, 2001   22
25               Sid'Ahmed Taya       Striker  Left Winger  Dec 29, 2001   22
26     16                Mingui       Striker  Left Winger  Nov 26, 2001   22
27               Gabriel Ajuchi       Striker  Left Winger  Sep 20, 2001   22
28     17         Taufek Bayoud       Striker  Left Winger  Mar 15, 2001   23
29                 Kiko Carmona       Striker  Left Winger  Dec 21, 2001   22
30                 Iván Sánchez       Striker  Left Winger   Sep 4, 2001   23
31                 Ahmed Chaibi       Striker  Left Winger  Aug 20, 2001   23
32               Álvaro Álvarez       Striker  Left Winger  Jun 28, 2001   23
33               Sergio Benítez       Striker  Left Winger  Apr 28, 2001   23
34                    Álex Loro       Striker  Left Winger  Sep 21, 2001   22
35     16            Dani Pérez       Striker  Left Winger   Mar 4, 2001   23
36             Alejandro Casado       Striker  Left Winger   Dec 3, 2001   22
37     21              Alvi Gil       Striker  Left Winger  Mar 21, 2001   23
38     20         Álex Monerris       Striker  Left Winger  Jun 16, 2001   23
39                 Jesús García       Striker  Left Winger  Oct 24, 2001   22
40                Ismael Agüero       Striker  Left Winger   Aug 7, 2001   23
41                  Álex Briega       Striker  Left Winger  Dec 19, 2001   22
42                  Ale Delgado       Striker  Left Winger  Oct 30, 2001   22
43                  Diego Pinto       Striker  Left Winger  Jul 27, 2001   23
44                  Jony García       Striker  Left Winger  Jul 21, 2001   23
45     19       Youssef Zayzoun       Striker  Left Winger   May 7, 2001   23
46                  Iván Chacón       Striker  Left Winger   Jan 1, 2001   23
47                        Toñin       Striker  Left Winger   Jul 2, 2001   23
48              Carlos Martínez       Striker  Left Winger  Oct 21, 2001   22
49                      Perotti       Striker  Left Winger  Jun 16, 2001   23
50     21        Javi Berenguer       Striker  Left Winger  Jun 25, 2001   23
51                Manex Asategi       Striker  Left Winger   Aug 5, 2001   23
52     22           Javi Vargas       Striker  Left Winger   Mar 6, 2001   23
53                 David Franco       Striker  Left Winger  Mar 28, 2001   23
54              Marco Diliberto       Striker  Left Winger   May 7, 2001   23
55      7  Juan Antonio Guirado       Striker  Left Winger  Mar 16, 2001   23
56     22     Roberto Fernández       Striker  Left Winger  Feb 12, 2001   23
57      7       Fernando Muriel       Striker  Left Winger  Apr 30, 2001   23
58                Suaibo Sanneh       Striker  Left Winger  Jun 16, 2001   23
59      9            Eric Pérez       Striker  Left Winger  May 18, 2001   23
60              Diego Fernández       Striker  Left Winger  Jan 17, 2001   23
61     23         Aramis García       Striker  Left Winger  Jan 21, 2001   23
62     16        Pelayo Morilla       Striker  Left Winger  Jul 12, 2001   23

                   Nationality Birth Country          Place of Birth
0                      [Spain]         Spain         Roquetas de Mar  \
1                      [Spain]         Spain         Barbate (Cádiz)
2                      [Spain]         Spain     Alcázar de San Juan
3                      [Spain]         Spain                  Málaga
4                      [Spain]         Spain                  Madrid
5                      [Spain]         Spain                Tarazona
6                      [Spain]         Spain               Barcelona
7                      [Spain]         Spain               Tarragona
8                      [Spain]         Spain           Fuerteventura
9                      [Spain]         Spain       Palma de Mallorca
10                     [Spain]         Spain               Zumárraga
11                     [Spain]         Spain                 Melilla
12            [Spain, Morocco]         Spain                  Madrid
13                     [Spain]         Spain  Donostia-San Sebastián
14                     [Spain]         Spain                  Málaga
15                     [Spain]         Spain                   Leioa
16                     [Spain]         Spain                 Granada
17                     [Spain]         Spain                Figueres
18                     [Spain]         Spain               Santander
19                     [Spain]         Spain               Barakaldo
20                     [Spain]         Spain                  Bilbao
21                     [Spain]         Spain                  Málaga
22                     [Spain]         Spain                  Murcia
23                     [Spain]         Spain                   Gijón
24  [Equatorial Guinea, Spain]         Spain       Palma de Mallorca
25         [Spain, Mauritania]         Spain              Las Palmas
26                     [Spain]         Spain                  Málaga
27            [Spain, Nigeria]         Spain                 Sevilla
28            [Spain, Morocco]         Spain                   Ceuta
29                     [Spain]         Spain
30                     [Spain]         Spain
31            [Morocco, Spain]         Spain
32                     [Spain]         Spain                Ayamonte
33                     [Spain]         Spain               Algeciras
34                     [Spain]         Spain             Ciudad Real
35                     [Spain]         Spain               Calamonte
36                     [Spain]         Spain                   Soria
37                     [Spain]         Spain              Valladolid
38                     [Spain]         Spain                Alicante
39                     [Spain]         Spain                Mallorca
40                     [Spain]         Spain               Santander
41                     [Spain]         Spain                  Madrid
42                     [Spain]         Spain  Santa Cruz de Tenerife
43                     [Spain]         Spain    La Palma del Condado
44                     [Spain]         Spain              La Orotava
45            [Spain, Morocco]         Spain                 Palamós
46                     [Spain]         Spain               Algeciras
47                     [Spain]         Spain                 Santoña
48                     [Spain]         Spain              Pontevedra
49                     [Spain]         Spain                  Gerena
50                     [Spain]         Spain                    Aspe
51                     [Spain]         Spain                 Durango
52                     [Spain]         Spain  Villanueva del Ariscal
53            [Spain, Ecuador]         Spain        Collado Villalba
54                     [Spain]         Spain                 Tafalla
55                     [Spain]         Spain                Marbella
56                     [Spain]         Spain                  Mérida
57                     [Spain]         Spain               Salamanca
58         [Spain, The Gambia]         Spain           Pineda de Mar
59                     [Spain]         Spain                   Ermua
60                     [Spain]         Spain               Santurtzi
61                     [Spain]         Spain               Salamanca
62                     [Spain]         Spain                  Oviedo

   Other Positions Height Market Value
0          AM   RW   1,74      €40.00m
1          RW   AM   1,75      €14.00m
2          RW   SS   1,77       €3.00m
3          CF   RW   1,73        €800k
4          RW   AM   1,74        €500k
5          RW   CF   1,80        €400k
6          AM   RW   1,83        €200k
7          AM   RW   1,75        €200k
8          RW   CF   1,75        €150k
9          SS   RW   1,75        €150k
10                               €100k
11              LB   1,86         €50k
12         CF   RW   1,82         €25k
13         RW   RB   1,75      €20.00m
14         RW   AM   1,64      €12.00m
15              RW   1,74       €2.20m
16         RW   CF   1,83        €800k
17              RW   1,75        €400k
18              RW   1,81        €300k
19              RW   1,74        €200k
20         AM   RW   1,85        €150k
21         AM   CM   1,82        €150k
22              RW   1,74        €100k
23         RW   CF               €100k
24              CF                €50k
25         RW   CF   1,80            -
26                   1,65            -
27         CF   RW                   -
28         RW   AM   1,78            -
29              RW   1,78            -
30                   1,67            -
31         RW   CF                   -
32              LB                   -
33                                   -
34                   1,70            -
35         RW   CF   1,78            -
36                   1,77            -
37         RW   CF                   -
38         RW   AM                   -
39              CF                   -
40                   1,76            -
41         RW   AM   1,78            -
42              RW   1,79            -
43                   1,72            -
44              RW   1,74            -
45         RW   CF   1,83            -
46                                   -
47                   1,70            -
48              SS                   -
49         RW   AM   1,70            -
50              CF                   -
51                   1,71            -
52         AM   RW                   -
53         RW   AM   1,68            -
54              CF   1,82            -
55              RW   1,79            -
56              RW                   -
57              RW   1,70            -
58              RW                   -
59              RW   1,80            -
60              AM   1,86            -
61         SS   RW   1,77            -
62                   1,82            -

## Merge all the dataframes into a single one and save the df into a csv file

In [206]:
df_merged = pd.concat([df_1985,df_1986,df_1987,df_1988,df_1989,df_1990,df_1991,df_1992,df_1993,df_1994,df_1995,df_1996,df_1997,df_1998,df_1999,df_2000,df_2001,df_2002,df_2003,df_2004,df_2005],ignore_index=True)

In [207]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 859 entries, 0 to 858
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           859 non-null    object
 1   Name             859 non-null    object
 2   Main Position    859 non-null    object
 3   Position         859 non-null    object
 4   Date of Birth    859 non-null    object
 5   Age              859 non-null    object
 6   Nationality      859 non-null    object
 7   Birth Country    859 non-null    object
 8   Place of Birth   859 non-null    object
 9   Other Positions  859 non-null    object
 10  Height           859 non-null    object
 11  Market Value     859 non-null    object
dtypes: object(12)
memory usage: 80.7+ KB

In [208]:
df_merged.to_csv("../../data/spain/spain_leftwingers.csv", header= True, index=False)