# Transfermarkt scrapping with Beautiful Soup & Selenium

## Imports

In [1]:
import re
import requests
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

## Webdriver options

In [2]:
options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
options.add_argument('--incognito')
#options.add_argument('--headless')

driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)
driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/1")

/var/folders/qw/qjxyt3tn1057c6j4pl5tb03c0000gn/T/ipykernel_40567/2000119249.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("../chromedriver-mac-arm64/chromedriver",options= options)

## Create dataframes and scrap the data from Transfermarkt

In [3]:
df_1985 = pd.DataFrame()
df_1986 = pd.DataFrame()
df_1987 = pd.DataFrame()
df_1988 = pd.DataFrame()
df_1989 = pd.DataFrame()
df_1990 = pd.DataFrame()
df_1991 = pd.DataFrame()
df_1992 = pd.DataFrame()
df_1993 = pd.DataFrame()
df_1994 = pd.DataFrame()
df_1995 = pd.DataFrame()
df_1996 = pd.DataFrame()
df_1997 = pd.DataFrame()
df_1998 = pd.DataFrame()
df_1999 = pd.DataFrame()
df_2000 = pd.DataFrame()
df_2001 = pd.DataFrame()
df_2002 = pd.DataFrame()
df_2003 = pd.DataFrame()
df_2004 = pd.DataFrame()
df_2005 = pd.DataFrame()

In [66]:
driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/1")
page_source = driver.page_source
rows = []
next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
count = 2

#print(len(next_buttons))

#for x in range(len(next_buttons)):
while (len(next_buttons)!=0) :
    
    if next_buttons[0].is_displayed():

        soup = BeautifulSoup(page_source, "html.parser")
        #next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        tables = soup.find_all('table')
        table = soup.find('table', class_ = 'items')  
      
        #Collect data for odd rows  
        for row in table.tbody.find_all('tr', class_="odd"):    
        # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Main Position': "Striker",
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Spain',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
            } )

        #Collect data for even rows
        for row in table.tbody.find_all('tr', class_="even"):    
        # Find all data for each column
            columns = row.find_all('td')
    
            if(columns != []):

                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Main Position': "Striker",
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Spain',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
            } )        

        driver.get("https://www.transfermarkt.com/detailsuche/spielerdetail/suche/46762278/page/" + "" + str(count))
        page_source = driver.page_source
        next_buttons = driver.find_elements(By.XPATH,"//a [@title='Go to the next page']")
        count +=1


page_source = driver.page_source
soup = BeautifulSoup(page_source, "html.parser")
tables = soup.find_all('table')
table = soup.find('table', class_ = 'items')  
      
#Collect data for odd rows        
for row in table.tbody.find_all('tr', class_="odd"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Main Position': "Striker",
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Spain',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
    } )

#Collect data for even rows
for row in table.tbody.find_all('tr', class_="even"):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
                
                nationalities=[]
                for nationality in columns[6]:
                    if nationality.get("title") is not None :
                        nationalities.append(nationality.get("title"))

                rows.append({
                'Number' : columns[0].text.strip(),
                'Name':columns[3].text.strip(),
                'Main Position': "Striker",
                'Position': columns[4].text.strip(),
                'Date of Birth': columns[5].text.split('(')[0],
                'Age': columns[5].text.split('(')[-1].replace(")",''),
                'Nationality': nationalities ,
                'Birth Country': 'Spain',
                'Place of Birth': columns[8].text.strip(),
                'Other Positions' : columns[9].text.strip(),
                'Height' : columns[10].text.strip(),
                'Market Value' : columns[11].text.strip()
    } )  

df_2005 = pd.DataFrame(rows)               
df_2005

,Number,Name,Main Position,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Other Positions,Height,Market Value
0,17,David Mella,Striker,Right Winger,"May 23, 2005",19,[Spain],Spain,Santiago de Compostela,LW,"1,69",€1.00m
1,,Jeremy Arévalo,Striker,Right Winger,"Mar 19, 2005",19,"[Spain, Ecuador]",Spain,Maliaño,CF,"1,80",€200k
2,7,Víctor Moreno,Striker,Right Winger,"Sep 30, 2005",18,[Spain],Spain,Granada,LW,"1,74",€100k
3,27,Javirro,Striker,Right Winger,"Aug 20, 2005",19,[Spain],Spain,Barcelona,,,€25k
4,,Cristian Martín,Striker,Right Winger,"Feb 23, 2005",19,[Spain],Spain,Antequera,LW AM,,-
5,12,Iván Pérez,Striker,Right Winger,"Jan 1, 2005",19,[Spain],Spain,Las Palmas de Gran Canaria,,,-
6,,Adrián Herrada,Striker,Right Winger,"Jan 28, 2005",19,[Spain],Spain,Alcoy,,"1,72",-
7,,Koke Mota,Striker,Right Winger,"Mar 5, 2005",19,[Spain],Spain,Fuenlabrada,LW CF,"1,88",-
8,,Luken Kesner,Striker,Right Winger,"Apr 18, 2005",19,"[Spain, United States]",Spain,Ibiza,AM,,-
9,9,Juan Carlos,Striker,Right Winger,"May 15, 2005",19,[Spain],Spain,Sanlucar de Barrameda,LW AM,"1,75",-
10,,Quique Escolano,Striker,Right Winger,"Feb 28, 2005",19,[Spain],Spain,Vélez,LW,"1,80",-
11,,Yidne Pinto,Striker,Right Winger,"Apr 20, 2005",19,"[Spain, Ethiopia]",Spain,Vitoria,LW CF,"1,83",-
12,,Kareem Tunde,Striker,Right Winger,"Aug 19, 2005",19,"[Spain, Nigeria]",Spain,Barcelona,LW CF,"1,77",-
13,11,Aingeru Olabarrieta,Striker,Right Winger,"Nov 14, 2005",18,[Spain],Spain,Luiaondo,LW,"1,82",€500k
14,22,Iñigo Arguibide,Striker,Right Winger,"Apr 19, 2005",19,[Spain],Spain,Pamplona,RB,"1,78",€150k
15,29,Abderrahman Akbache,Striker,Right Winger,"Aug 25, 2005",19,"[Algeria, Spain]",Spain,Vitoria-Gasteiz,LW RB,"1,81",€25k
16,14,Adrián Sanmartín,Striker,Right Winger,"Jul 28, 2005",19,[Spain],Spain,Murcia,SS LW,"1,70",€25k
17,,Lakatus,Striker,Right Winger,"Jan 1, 2005",19,[Spain],Spain,Murcia,LW,,-
18,,Unai Garcés,Striker,Right Winger,"Jun 12, 2005",19,[Spain],Spain,Bilbao,LW AM,"1,86",-
19,28,Álvaro Moreno,Striker,Right Winger,"May 14, 2005",19,[Spain],Spain,,AM LW,,-
20,,Alberto Páez,Striker,Right Winger,"Jan 1, 2005",19,[Spain],Spain,Las Palmas de Gran Canaria,LW,,-
21,,Andreas Membrives,Striker,Right Winger,"Aug 19, 2005",19,"[Spain, Dominican Republic]",Spain,Valencia,AM,"1,74",-
22,24,Diego Díaz,Striker,Right Winger,"May 31, 2005",19,[Spain],Spain,Santander,LW CM,"1,73",-
23,,Javi Gambra,Striker,Right Winger,"Jan 3, 2005",19,[Spain],Spain,Pamplona,LW,"1,70",-
24,,Juanjo Linares,Striker,Right Winger,"Feb 19, 2005",19,[Spain],Spain,Almería,,,-
25,21,Izan Sarmiento,Striker,Right Winger,"Mar 2, 2005",19,[Spain],Spain,Manresa,,,-
26,14,Javier Martínez,Striker,Right Winger,"Jan 22, 2005",19,[Spain],Spain,Nájera,,"1,70",-
27,,Enrique Peña,Striker,Right Winger,"Apr 25, 2005",19,"[Peru, Spain]",Spain,Toledo,LW AM,"1,73",-
28,,Dani Sánchez,Striker,Right Winger,"Dec 10, 2005",18,[Spain],Spain,,RB,,-
29,,Nil Calderó,Striker,Right Winger,"May 2, 2005",19,[Spain],Spain,Claravalls,,,-
30,,Jon Landa,Striker,Right Winger,"Feb 2, 2005",19,[Spain],Spain,Amurrio,LW,,-
31,,Álvaro Arquellada,Striker,Right Winger,"Jun 28, 2005",19,[Spain],Spain,Dos Hermanas,RB CM,"1,75",-
32,,Nabil Ghailán,Striker,Right Winger,"May 10, 2005",19,"[Morocco, Spain]",Spain,,LW,,-
33,,Cayetano Ruiz,Striker,Right Winger,"Apr 20, 2005",19,[Spain],Spain,Logroño,,"1,73",-
34,17,Aimar Vicandi,Striker,Right Winger,"Feb 9, 2005",19,[Spain],Spain,Bilbao,LW SS,"1,83",-
35,17,Michael Dacosta González,Striker,Right Winger,"Mar 5, 2005",19,"[Spain, Equatorial Guinea]",Spain,Alicante,LW,"1,86",-
36,40,Adam Arvelo,Striker,Right Winger,"May 31, 2005",19,[Spain],Spain,Candelaria,AM LW,"1,76",-
37,,Pol Fortuny,Striker,Right Winger,"Mar 11, 2005",19,[Spain],Spain,Tarragona,AM LW,"1,75",-
38,11,Caden McLoughlin,Striker,Right Winger,"Mar 6, 2005",19,"[Ireland, Spain]",Spain,"Costa del Sol, Málaga",CF SS,"1,81",-

In [62]:
with pd.option_context('display.max_rows',None, 'display.max_columns',None):print(df_2001)

   Number                  Name Main Position      Position  Date of Birth
0       7        Rober González       Striker  Right Winger   Jan 8, 2001   \
1      17        Jofre Carreras       Striker  Right Winger  Jun 17, 2001
2      11           Luismi Cruz       Striker  Right Winger  May 23, 2001
3      18           Unai Ropero       Striker  Right Winger  Nov 20, 2001
4      11             Manu Pozo       Striker  Right Winger  Dec 12, 2001
5      19       Victor Valverde       Striker  Right Winger  Dec 26, 2001
6                  Jonny Arriba       Striker  Right Winger   Nov 1, 2001
7      17        Sergio Navarro       Striker  Right Winger  Feb 16, 2001
8      11          Jesús Villar       Striker  Right Winger  Nov 18, 2001
9           Alejandro Ibarrondo       Striker  Right Winger  May 16, 2001
10                  Óscar Gonpi       Striker  Right Winger  Jul 11, 2001
11                David Barrios       Striker  Right Winger   Apr 7, 2001
12     11         Antonio Pavón       Striker  Right Winger   Nov 4, 2001
13     23              Adu Ares       Striker  Right Winger  Oct 12, 2001
14                 Ilyas Chaira       Striker  Right Winger   Feb 2, 2001
15     21           Teto Martín       Striker  Right Winger  Sep 13, 2001
16     20       Suleiman Camara       Striker  Right Winger   Dec 7, 2001
17     19         Jaume Cuéllar       Striker  Right Winger  Aug 23, 2001
18      7         Jordan Lamela       Striker  Right Winger   Jan 1, 2001
19     17         Nils Mortimer       Striker  Right Winger  Jun 11, 2001
20     17           Unai García       Striker  Right Winger  Oct 14, 2001
21            Mateo Gandarillas       Striker  Right Winger  Jan 20, 2001
22          Maurizio Pochettino       Striker  Right Winger  Mar 30, 2001
23                  Nacho Muñoz       Striker  Right Winger   Dec 3, 2001
24         Christian Vassilakis       Striker  Right Winger  Feb 28, 2001
25     18        Álvaro Barrena       Striker  Right Winger  Aug 24, 2001
26      7         Samu Aparicio       Striker  Right Winger  Sep 16, 2001
27     11         Diego Jiménez       Striker  Right Winger   Jan 1, 2001
28                Kelly Jackson       Striker  Right Winger  Mar 20, 2001
29                 Fran Barberá       Striker  Right Winger   Jan 1, 2001
30                  Juan España       Striker  Right Winger  Feb 14, 2001
31               Raúl Fernández       Striker  Right Winger  Nov 26, 2001
32     10                Luispa       Striker  Right Winger  Jul 24, 2001
33               Jorge Martínez       Striker  Right Winger  May 18, 2001
34                Raúl Carrasco       Striker  Right Winger  Apr 28, 2001
35               Álvaro Cuellar       Striker  Right Winger  Jul 27, 2001
36               Kilian Cabrero       Striker  Right Winger   Feb 1, 2001
37                Sergio Mulero       Striker  Right Winger  Sep 10, 2001
38     10       Álvaro González       Striker  Right Winger   Nov 4, 2001
39                   Ivan Mbika       Striker  Right Winger  Jul 31, 2001
40     12           Markel Pita       Striker  Right Winger  Sep 28, 2001
41         Gonzalo De la Morena       Striker  Right Winger  Aug 23, 2001
42                   Alex Pilas       Striker  Right Winger   Jan 1, 2001
43              Juanma Trujillo       Striker  Right Winger  Mar 17, 2001
44              Mariano Carmona       Striker  Right Winger  Jun 20, 2001
45              Sergio González       Striker  Right Winger  Feb 15, 2001
46               Pablo González       Striker  Right Winger  Jul 28, 2001
47                        Rubio       Striker  Right Winger   Mar 3, 2001
48               Richard Franco       Striker  Right Winger  Sep 22, 2001
49                Enric Baquero       Striker  Right Winger  Aug 26, 2001
50              Guille Thompson       Striker  Right Winger  Apr 30, 2001
51     18             Juan Díaz       Striker  Right Winger  Jun 11, 2001
52     19          Luis Jiménez       Striker  Right Winger  Feb 20, 2001
53     11            Joel Febas       Striker  Right Winger  Dec 18, 2001
54                    Óscar Gil       Striker  Right Winger  Jan 15, 2001
55     14          José Contell       Striker  Right Winger   Apr 6, 2001
56                  Adrián Vich       Striker  Right Winger  Mar 15, 2001
57      9         Lucas Álvarez       Striker  Right Winger  Nov 15, 2001
58                  Álex Piedra       Striker  Right Winger   Mar 7, 2001
59                 Urko Collado       Striker  Right Winger  Feb 27, 2001
60     17             Rodri Val       Striker  Right Winger   Jan 5, 2001
61                Guille Lozano       Striker  Right Winger   Apr 4, 2001
62                         Koke       Striker  Right Winger  Aug 23, 2001

   Age             Nationality Birth Country             Place of Birth
0   23                 [Spain]         Spain                     Mérida  \
1   23                 [Spain]         Spain                     Girona
2   23                 [Spain]         Spain   El Puerto de Santa María
3   22                 [Spain]         Spain            Vitoria-Gasteiz
4   22                 [Spain]         Spain                  Casariche
5   22         [Spain, Brazil]         Spain                   Figueres
6   22                 [Spain]         Spain             La Vall d'Uixó
7   23                 [Spain]         Spain                     Madrid
8   22                 [Spain]         Spain                    Maliaño
9   23                 [Spain]         Spain                     Bilbao
10  23                 [Spain]         Spain                   Badalona
11  23                 [Spain]         Spain                    Sevilla
12  22                 [Spain]         Spain                 Monesterio
13  22  [Spain, Guinea-Bissau]         Spain                     Bilbao
14  23        [Morocco, Spain]         Spain                     Ripoll
15  22                 [Spain]         Spain     Santa Cruz de Tenerife
16  22     [Spain, The Gambia]         Spain                Sant Celoni
17  23        [Bolivia, Spain]         Spain                 Granollers
18  23                 [Spain]         Spain               San Fernando
19  23                 [Spain]         Spain                     Málaga
20  22                 [Spain]         Spain     Donostia-San Sebastián
21  23                 [Spain]         Spain                    Bádames
22  23      [Spain, Argentina]         Spain                  Barcelona
23  22                 [Spain]         Spain                     Beniel
24  23         [Greece, Spain]         Spain                   Valencia
25  23                 [Spain]         Spain                   Azuqueca
26  22                 [Spain]         Spain                 Valladolid
27  23                 [Spain]         Spain                     Murcia
28  23        [Spain, Nigeria]         Spain               Porto Cristo
29  23                 [Spain]         Spain                     Murcia
30  23                 [Spain]         Spain  La Linea de la Concepcion
31  22                 [Spain]         Spain                    Granada
32  23                 [Spain]         Spain                      Yecla
33  23                 [Spain]         Spain                     Murcia
34  23                 [Spain]         Spain                     Huesca
35  23                 [Spain]         Spain                 Valladolid
36  23                 [Spain]         Spain                     Mataró
37  22                 [Spain]         Spain                   Sabadell
38  22                 [Spain]         Spain                Valsequillo
39  23                 [Spain]         Spain                     Madrid
40  22                 [Spain]         Spain
41  23                 [Spain]         Spain
42  23                 [Spain]         Spain                    Águilas
43  23                 [Spain]         Spain         Llanos de Don Juan
44  23                 [Spain]         Spain                     Murcia
45  23                 [Spain]         Spain                  Algeciras
46  23                 [Spain]         Spain             Puebla del Río
47  23                 [Spain]         Spain                     Madrid
48  22       [Colombia, Spain]         Spain                     Arnedo
49  22                 [Spain]         Spain                  Barcelona
50  23        [Spain, England]         Spain                     Oviedo
51  23                 [Spain]         Spain
52  23                 [Spain]         Spain                    Corella
53  22                 [Spain]         Spain                     Lleida
54  23                 [Spain]         Spain                      Moaña
55  23                 [Spain]         Spain                   Valencia
56  23                 [Spain]         Spain                     Bilbao
57  22                 [Spain]         Spain                     Utrera
58  23                 [Spain]         Spain        Pozo de los Frailes
59  23                 [Spain]         Spain                    Abadiño
60  23                 [Spain]         Spain                      Aurín
61  23                 [Spain]         Spain                  Santomera
62  23                 [Spain]         Spain                     Burgos

   Other Positions Height Market Value
0          LW   AM   1,69       €2.50m
1               LW   1,75       €1.80m
2          AM   LW   1,66        €800k
3          SS   LW   1,88        €500k
4               LW   1,68        €400k
5               AM               €250k
6          AM   LW   1,76        €225k
7               LW   1,76        €150k
8          CF   LW   1,84        €100k
9               RB   1,83        €100k
10                   1,74         €50k
11                   1,76         €25k
12              LW                   -
13              LW   1,83       €2.00m
14              LW              €1.60m
15         AM   LW   1,75        €700k
16                               €500k
17         LW   SS   1,80        €300k
18              AM   1,81        €225k
19         LW   AM   1,78        €200k
20              LW   1,76        €150k
21         LW   RB   1,73        €100k
22              LW               €100k
23              LW   1,84         €50k
24         LW   SS   1,78         €25k
25         LW   CF                   -
26         LW   CF                   -
27                                   -
28              SS                   -
29                                   -
30                                   -
31         SS   LW   1,86            -
32         SS   LW   1,76            -
33         RB   LW   1,80            -
34         SS   CF   1,82            -
35              LW                   -
36         LW   SS   1,73            -
37              LW                   -
38         AM   LW   1,70            -
39                                   -
40              LW   1,83            -
41         SS   LW   1,72            -
42                   1,72            -
43                                   -
44         CF   LW   1,85            -
45         SS   LW                   -
46                                   -
47                   1,70            -
48         LW   RB   1,69            -
49              LW   1,70            -
50              LW                   -
51         AM   LW                   -
52         SS   LW   1,82            -
53         SS   CF   1,71            -
54              CF                   -
55              CF                   -
56              LW                   -
57              LW                   -
58              AM   1,76            -
59         LW   CF   1,79            -
60              LW   1,78            -
61                   1,74            -
62         LW   CF                   -

## Merge all the dataframes into a single one and save the df into a csv file

In [67]:
df_merged = pd.concat([df_1985,df_1986,df_1987,df_1988,df_1989,df_1990,df_1991,df_1992,df_1993,df_1994,df_1995,df_1996,df_1997,df_1998,df_1999,df_2000,df_2001,df_2002,df_2003,df_2004,df_2005],ignore_index=True)

In [68]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1047 entries, 0 to 1046
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           1047 non-null   object
 1   Name             1047 non-null   object
 2   Main Position    1047 non-null   object
 3   Position         1047 non-null   object
 4   Date of Birth    1047 non-null   object
 5   Age              1047 non-null   object
 6   Nationality      1047 non-null   object
 7   Birth Country    1047 non-null   object
 8   Place of Birth   1047 non-null   object
 9   Other Positions  1047 non-null   object
 10  Height           1047 non-null   object
 11  Market Value     1047 non-null   object
dtypes: object(12)
memory usage: 98.3+ KB

In [69]:
df_merged.to_csv("../../data/spain/spain_rightwingers.csv", header= True, index=False)